// Generated by the Ruva transpiler — do not edit
#![allow(unused, dead_code, non_snake_case, non_camel_case_types)]

enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
    Rem,
    Eq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
    And,
    Or,
    BitAnd,
    BitOr,
    BitXor,
    Shl,
    Shr,
}

enum UnaryOp {
    Neg,
    Not,
    Deref,
}

struct Program {
    items: Vec<Item>,
}

enum Item {
    Function(FunctionDef),
    Struct(StructDef),
    Enum(EnumDef),
    Impl(ImplBlock),
    Trait(TraitDef),
    Import(ImportDef),
    ExternBlock(ExternBlock),
}

struct FunctionDef {
    is_pub: bool,
    name: string,
    params: Vec<Param>,
    return_type: Option<Type>,
    body: Block,
}

struct Param {
    name: string,
    ty: Type,
}

struct StructDef {
    is_pub: bool,
    name: string,
    fields: Vec<FieldDef>,
}

struct FieldDef {
    is_pub: bool,
    name: string,
    ty: Type,
}

struct EnumDef {
    is_pub: bool,
    name: string,
    variants: Vec<EnumVariant>,
}

struct EnumVariant {
    name: string,
    fields: Vec<Type>,
}

struct ImplBlock {
    self_type: Type,
    trait_name: Option<Type>,
    methods: Vec<FunctionDef>,
}

struct TraitDef {
    is_pub: bool,
    name: string,
    methods: Vec<TraitMethod>,
}

struct TraitMethod {
    name: string,
    params: Vec<Param>,
    return_type: Option<Type>,
    default_body: Option<Block>,
}

struct ImportDef {
    path: string,
}

struct ExternBlock {
    abi: string,
    items: Vec<ExternItem>,
}

enum ExternItem {
    Function(bool, string, Vec<Param>, Option<Type>),
    Static(bool, string, Type),
}

enum Type {
    Name(string),
    Generic(string, Vec<Type>),
    Reference(Box<Type>, bool),
    Slice(Box<Type>),
    Array(Box<Type>, Option<Box<Expr>>),
    Tuple(Vec<Type>),
    Function(Vec<Type>, Box<Type>),
    Unit,
    RawPointer(Box<Type>, bool),
}

struct Block {
    stmts: Vec<Stmt>,
    expr: Option<Box<Expr>>,
}

enum Stmt {
    Let(string, Option<Type>, bool, Expr),
    Expr(Expr),
    Return(Option<Expr>),
    If(Expr, Block, Option<ElseKind>),
    For(string, Expr, Block),
    While(Expr, Block),
    Loop(Block),
    Break(Option<Expr>),
    Continue,
    Match(Expr, Vec<MatchArm>),
    Unsafe(Block),
}

enum ElseKind {
    If(Expr, Block),
    Else(Block),
}

struct MatchArm {
    pattern: Pattern,
    body: Expr,
}

enum Pattern {
    Wildcard,
    Ident(string),
    Literal(Expr),
    Enum(Vec<string>, Vec<Pattern>),
    Or(Vec<Pattern>),
}

enum Expr {
    Int(i64),
    Float(f64),
    Str(string),
    Bool(bool),
    Null,
    Array(Vec<Expr>),
    Tuple(Vec<Expr>),
    Range(Box<Expr>, Box<Expr>, bool),
    Ident(string),
    Path(Vec<string>),
    Self_,
    Binary(BinOp, Box<Expr>, Box<Expr>),
    Unary(UnaryOp, Box<Expr>),
    Assign(Box<Expr>, Box<Expr>),
    CompoundAssign(BinOp, Box<Expr>, Box<Expr>),
    Call(Box<Expr>, Vec<Expr>),
    MethodCall(Box<Expr>, string, Vec<Expr>),
    Field(Box<Expr>, string),
    Index(Box<Expr>, Box<Expr>),
    Closure(Vec<ClosureParam>, Box<Expr>),
    Block(Block),
    If(Box<Expr>, Block, Option<Box<Expr>>),
    Match(Box<Expr>, Vec<MatchArm>),
    Loop(Block),
    Macro(string, Vec<Expr>),
    Reference(Box<Expr>, bool),
    Deref(Box<Expr>),
    Cast(Box<Expr>, Type),
    StructLiteral(Box<Expr>, Vec<(string, Expr)>),
    UnsafeBlock(Block),
    Sizeof(Type),
}

struct ClosureParam {
    name: string,
    is_ref: bool,
    is_mut: bool,
}

