use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

pub struct CodeGen {
    output: String,
    indent: usize,

    import_map: std::collections::HashMap<String, String>,

    dependencies: Vec<(String, String)>,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            output: String::with_capacity(4096),
            indent: 0,
            import_map: Self::build_import_map(),
            dependencies: Vec::new(),
        }
    }


    fn build_import_map() -> std::collections::HashMap<String, String> {
        let mut map = std::collections::HashMap::new();


        map.insert("ruva::graphics::opengl".into(), "gl".into());
        map.insert("ruva::graphics::opengl::Window".into(), "glutin".into());
        map.insert("ruva::graphics::opengl::Context".into(), "gl".into());


        map.insert("ruva::graphics::vulkan".into(), "vulkano".into());
        map.insert("ruva::graphics::vulkan::Instance".into(), "vulkano".into());
        map.insert("ruva::graphics::vulkan::Device".into(), "vulkano".into());


        map.insert("ruva::graphics::directx11".into(), "winapi".into());
        map.insert("ruva::graphics::directx12".into(), "winapi".into());


        map.insert("ruva::browser::wasm".into(), "wasm-bindgen".into());
        map.insert("ruva::browser::dom".into(), "web-sys".into());
        map.insert("ruva::browser::canvas".into(), "web-sys".into());
        map.insert("ruva::browser::webgl".into(), "web-sys".into());
        map.insert("ruva::browser::fetch".into(), "gloo-net".into());
        map.insert("ruva::browser::websocket".into(), "gloo-net".into());


        map.insert("ruva::video".into(), "ffmpeg-next".into());
        map.insert("ruva::video::VideoDecoder".into(), "ffmpeg-next".into());
        map.insert("ruva::video::VideoEncoder".into(), "ffmpeg-next".into());
        map.insert("ruva::video::filter".into(), "ffmpeg-next".into());


        map.insert("ruva::anticheat::memory".into(), "winapi".into());
        map.insert("ruva::anticheat::process".into(), "winapi".into());
        map.insert("ruva::anticheat::debug".into(), "winapi".into());
        map.insert("ruva::anticheat::tamper".into(), "winapi".into());
        map.insert("ruva::anticheat::crypto".into(), "aes-gcm".into());

        map
    }


    pub fn has_external_dependencies(&self) -> bool {
        !self.dependencies.is_empty()
    }

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        writeln!(self.output, "{}", s).unwrap();
    }

    pub fn generate_rust(&mut self, program: &Program) -> String {

        self.writeln("// Generated by the Ruva transpiler — do not edit");
        self.writeln("#![allow(unused, dead_code, non_snake_case, non_camel_case_types)]");
        self.writeln("");


        for item in &program.items {
            if let Item::Import(imp) = item {
                self.collect_dependencies(&imp.path);
            }
        }


        if !self.dependencies.is_empty() {
            self.writeln("// External crate imports");
            let deps: Vec<String> = self.dependencies.iter().map(|(n, _)| n.clone()).collect();
            for name in &deps {
                self.writeln(&format!("use {};", name));
            }
            self.writeln("");
        }


        for item in &program.items {
            self.gen_item(item);
        }

        std::mem::take(&mut self.output)
    }


    fn collect_dependencies(&mut self, path: &str) {
        if path.starts_with("ruva::") {

            if let Some(crate_name) = self.import_map.get(path) {

                if !self.dependencies.iter().any(|(n, _)| n == crate_name) {

                    let version = match crate_name.as_str() {
                        "gl" => "0.14",
                        "glutin" => "0.31",
                        "vulkano" => "0.34",
                        "winapi" => "0.3",
                        "wasm-bindgen" => "0.2",
                        "web-sys" => "0.3",
                        "gloo-net" => "0.4",
                        "ffmpeg-next" => "6.0",
                        "aes-gcm" => "0.10",
                        "anyhow" => "1",
                        _ => "0.1",
                    };
                    self.dependencies.push((crate_name.clone(), version.into()));
                }
            }
        }
    }



    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Enum(e) => self.gen_enum(e),
            Item::Class(c) => self.gen_class(c),
            Item::Impl(imp) => self.gen_impl(imp),
            Item::Trait(t) => self.gen_trait(t),
            Item::TypeAlias(ta) => self.gen_type_alias(ta),
            Item::Import(imp) => self.gen_import(imp),
            Item::Use(u) => self.gen_use(u),
            Item::Attribute(attr) => self.gen_attribute(attr),
            Item::Module(m) => self.gen_module(m),
            Item::ExternBlock(eb) => self.gen_extern_block(eb),
            Item::Interface(iface) => self.gen_interface(iface),
            Item::Package(pkg) => self.gen_package(pkg),
            Item::Comptime(ct) => self.gen_comptime(ct),
            Item::Decorated(dec) => self.gen_decorated(dec),
            Item::TryCatch(tc) => self.gen_try_catch(tc),
            Item::Throw(th) => self.gen_throw(th),
            Item::ListComp(lc) => self.gen_list_comp(lc),
        }
    }



    fn gen_function(&mut self, f: &FunctionDef) {
        if f.is_test {
            self.writeln("#[test]");
        }

        let vis = if f.is_pub { "pub " } else { "" };
        let name = &f.name;


        let generics = if f.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = f.generics.iter().map(|g| {
                if g.bounds.is_empty() {
                    g.name.clone()
                } else {
                    let bounds: Vec<String> = g.bounds.iter().map(|b| self.type_str(b)).collect();
                    format!("{}: {}", g.name, bounds.join(" + "))
                }
            }).collect();
            format!("<{}>", params.join(", "))
        };


        let params: Vec<String> = f.params.iter().map(|p| {
            if let Type::SelfType = &p.ty {
                let ref_str = if p.is_ref { "&" } else { "" };
                let mut_str = if p.is_mut { "mut " } else { "" };
                format!("{}{}self", ref_str, mut_str)
            } else {
                let ref_str = if p.is_ref { "&" } else { "" };
                let mut_str = if p.is_mut { "mut " } else { "" };
                let ty = self.type_str(&p.ty);
                format!("{}{}{}: {}", ref_str, mut_str, p.name, ty)
            }
        }).collect();


        let ret = match &f.return_type {
            Some(ty) => format!(" -> {}", self.type_str(ty)),
            None => String::new(),
        };

        let unsafe_str = if f.is_unsafe { "unsafe " } else { "" };
        self.writeln(&format!("{}{}fn {}{}({}){}", vis, unsafe_str, name, generics, params.join(", "), ret));
        self.gen_block(&f.body);
        self.writeln("");
    }



    fn gen_struct(&mut self, s: &StructDef) {
        let vis = if s.is_pub { "pub " } else { "" };


        if !s.derives.is_empty() {
            let derives = s.derives.join(", ");
            self.writeln(&format!("#[derive({})]", derives));
        }


        let generics = if s.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = s.generics.iter().map(|g| g.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };

        self.writeln(&format!("{}struct {}{} {{", vis, s.name, generics));
        self.indent += 1;

        for field in &s.fields {
            let vis = if field.is_pub { "pub " } else { "" };
            let ty = self.type_str(&field.ty);
            self.writeln(&format!("{}{}: {},", vis, field.name, ty));
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }



    fn gen_enum(&mut self, e: &EnumDef) {
        let vis = if e.is_pub { "pub " } else { "" };
        let generics = if e.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = e.generics.iter().map(|g| g.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };
        self.writeln(&format!("{}enum {}{} {{", vis, e.name, generics));
        self.indent += 1;

        for variant in &e.variants {
            if variant.fields.is_empty() {
                self.writeln(&format!("{},", variant.name));
            } else {
                let field_strs: Vec<String> = variant.fields.iter().map(|t| self.type_str(t)).collect();
                self.writeln(&format!("{}({}),", variant.name, field_strs.join(", ")));
            }
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }



    fn gen_class(&mut self, c: &ClassDef) {
        let vis = if c.is_pub { "pub " } else { "" };


        if !c.derives.is_empty() {
            let derives = c.derives.join(", ");
            self.writeln(&format!("#[derive({})]", derives));
        }


        self.writeln(&format!("{}struct {} {{", vis, c.name));
        self.indent += 1;

        for field in &c.fields {
            let vis = if field.is_pub { "pub " } else { "" };
            let mut_str = if field.is_mut { "mut " } else { "" };
            let ty = self.type_str(&field.ty);
            self.writeln(&format!("{}{}{}: {},", vis, mut_str, field.name, ty));
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");


        self.gen_class_methods(c);
    }

    fn gen_class_methods(&mut self, c: &ClassDef) {
        let generics = if c.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = c.generics.iter().map(|g| g.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };

        self.writeln(&format!("impl{} {} {{", generics, c.name));
        self.indent += 1;

        for method in &c.methods {
            self.gen_function(method);
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }



    fn gen_impl(&mut self, imp: &ImplBlock) {
        let generics = if imp.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = imp.generics.iter().map(|g| g.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };

        let self_type = self.type_str(&imp.self_type);

        if let Some(ref trait_name) = imp.trait_name {
            let trait_str = self.type_str(trait_name);
            self.writeln(&format!("impl{} {} for {} {{", generics, trait_str, self_type));
        } else {
            self.writeln(&format!("impl{} {} {{", generics, self_type));
        }

        self.indent += 1;

        for method in &imp.methods {
            self.gen_function(method);
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }



    fn gen_trait(&mut self, t: &TraitDef) {
        let vis = if t.is_pub { "pub " } else { "" };

        let generics = if t.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = t.generics.iter().map(|g| g.name.clone()).collect();
            format!("<{}>", params.join(", "))
        };

        self.writeln(&format!("{}trait {}{} {{", vis, t.name, generics));
        self.indent += 1;

        for method in &t.methods {
            let params: Vec<String> = method.params.iter().map(|p| {
                if let Type::SelfType = &p.ty {
                    let ref_str = if p.is_ref { "&" } else { "" };
                    let mut_str = if p.is_mut { "mut " } else { "" };
                    format!("{}{}self", ref_str, mut_str)
                } else {
                    let ty = self.type_str(&p.ty);
                    format!("{}: {}", p.name, ty)
                }
            }).collect();

            let ret = match &method.return_type {
                Some(ty) => format!(" -> {}", self.type_str(ty)),
                None => String::new(),
            };

            if let Some(ref body) = method.default_body {
                self.writeln(&format!("fn {}({}){} {{", method.name, params.join(", "), ret));
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.writeln("}");
            } else {
                self.writeln(&format!("fn {}({}){};", method.name, params.join(", "), ret));
            }
        }

        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }



    fn gen_type_alias(&mut self, ta: &TypeAliasDef) {
        let vis = if ta.is_pub { "pub " } else { "" };
        let ty = self.type_str(&ta.ty);
        self.writeln(&format!("{}type {} = {};", vis, ta.name, ty));
        self.writeln("");
    }



    fn gen_import(&mut self, imp: &ImportDef) {

        if imp.path.starts_with("ruva::") {
            if let Some(crate_name) = self.import_map.get(&imp.path) {
                if let Some(ref alias) = imp.alias {
                    self.writeln(&format!("use {} as {};", crate_name, alias));
                }


            }
        } else {

            if let Some(ref alias) = imp.alias {
                self.writeln(&format!("use {} as {};", imp.path, alias));
            } else {
                self.writeln(&format!("use {};", imp.path));
            }
        }
    }



    fn gen_attribute(&mut self, attr: &Attribute) {
        if attr.args.is_empty() {
            self.writeln(&format!("#[{}]", attr.name));
        } else {
            let args = attr.args.join(", ");
            self.writeln(&format!("#[{}({})]", attr.name, args));
        }
        self.gen_item(&attr.item);
    }



    fn gen_use(&mut self, u: &UseDef) {
        let path_str = u.path.join("::");
        if u.wildcard {
            self.writeln(&format!("use {}::*;", path_str));
        } else if !u.selective.is_empty() {
            let items: Vec<String> = u.selective.iter().map(|item| {
                if let Some(ref alias) = item.alias {
                    format!("{} as {}", item.name, alias)
                } else {
                    item.name.clone()
                }
            }).collect();
            self.writeln(&format!("use {}::{{{}}};", path_str, items.join(", ")));
        } else if let Some(ref alias) = u.alias {
            self.writeln(&format!("use {} as {};", path_str, alias));
        } else {
            self.writeln(&format!("use {};", path_str));
        }
    }



    fn gen_module(&mut self, m: &ModDef) {
        let vis = if m.is_pub { "pub " } else { "" };
        if let Some(ref body) = m.body {

            self.writeln(&format!("{}mod {} {{", vis, m.name));
            self.indent += 1;
            for item in body {
                self.gen_item(item);
            }
            self.indent -= 1;
            self.writeln("}");
        } else {

            self.writeln(&format!("{}mod {};", vis, m.name));
        }
        self.writeln("");
    }

    fn gen_extern_block(&mut self, eb: &ExternBlock) {
        self.writeln(&format!("extern \"{}\" {{", eb.abi));
        self.indent += 1;
        let items: Vec<ExternItem> = eb.items.iter().cloned().collect();
        for item in &items {
            match item {
                ExternItem::Function { is_pub, ref name, ref params, ref return_type } => {
                    let vis = if *is_pub { "pub " } else { "" };
                    let params_str: Vec<String> = params.iter().map(|p| {
                        format!("{}: {}", p.name, self.type_str(&p.ty))
                    }).collect();
                    let ret = match return_type {
                        Some(ref t) => format!(" -> {}", self.type_str(t)),
                        None => String::new(),
                    };
                    self.writeln(&format!("{}fn {}({}){};", vis, name, params_str.join(", "), ret));
                }
                ExternItem::Static { is_pub, is_mut, ref name, ref ty } => {
                    let vis = if *is_pub { "pub " } else { "" };
                    let mutability = if *is_mut { "mut " } else { "" };
                    let ty_str = self.type_str(ty);
                    self.writeln(&format!("{}static {}{}: {};", vis, mutability, name, ty_str));
                }
                ExternItem::Const { is_pub, ref name, ref ty, value: _ } => {
                    let vis = if *is_pub { "pub " } else { "" };
                    let ty_str = self.type_str(ty);
                    self.writeln(&format!("{}const {}: {};", vis, name, ty_str));
                }
            }
        }
        self.indent -= 1;
        self.writeln("}");
    }



    fn gen_block(&mut self, block: &Block) {
        self.writeln("{");
        self.indent += 1;

        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }

        if let Some(ref expr) = block.expr {
            self.write_indent();
            self.gen_expr(expr);
            self.output.push('\n');
        }

        self.indent -= 1;
        self.writeln("}");
    }



    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, ty, is_mut, value } => {
                let mut_str = if *is_mut { "mut " } else { "" };
                let pat_str = self.pattern_str(pattern);
                let ty_str = match ty {
                    Some(t) => format!(": {}", self.type_str(t)),
                    None => String::new(),
                };
                self.write_indent();
                write!(self.output, "let {}{}{}", mut_str, pat_str, ty_str).unwrap();
                self.output.push_str(" = ");
                self.gen_expr(value);
                self.output.push_str(";\n");
            }
            Stmt::Expr(expr) => {
                self.write_indent();
                self.gen_expr(expr);
                self.output.push_str(";\n");
            }
            Stmt::Return(expr) => {
                self.write_indent();
                if let Some(e) = expr {
                    write!(self.output, "return ").unwrap();
                    self.gen_expr(e);
                    self.output.push_str(";\n");
                } else {
                    self.output.push_str("return;\n");
                }
            }
            Stmt::If { condition, then_body, else_body } => {
                self.write(&format!("if "));
                self.gen_expr(condition);
                self.output.push(' ');
                self.gen_block(then_body);

                if let Some(else_kind) = else_body {


                    self.output.truncate(self.output.trim_end_matches('\n').len());
                    match else_kind {
                        ElseKind::If(cond, body) => {
                            self.output.push_str(" else if ");
                            self.gen_expr(cond);
                            self.output.push(' ');
                            self.gen_block(body);
                        }
                        ElseKind::Else(body) => {
                            self.output.push_str(" else ");
                            self.gen_block(body);
                        }
                    }
                }
            }
            Stmt::For { pattern, iterable, body } => {
                let pat_str = self.pattern_str(pattern);
                self.write_indent();
                write!(self.output, "for {} in ", pat_str).unwrap();

                if matches!(iterable, Expr::Array(_)) {
                    self.gen_expr(iterable);
                    self.output.push_str(".iter()");
                } else {
                    self.gen_expr(iterable);
                }
                self.output.push(' ');
                self.gen_block(body);
            }
            Stmt::While { condition, body } => {
                self.write_indent();
                self.output.push_str("while ");
                self.gen_expr(condition);
                self.output.push(' ');
                self.gen_block(body);
            }
            Stmt::WhileLet { pattern, value, body } => {
                let pat_str = self.pattern_str(pattern);
                self.write_indent();
                write!(self.output, "while let {} = ", pat_str).unwrap();
                self.gen_expr(value);
                self.output.push(' ');
                self.gen_block(body);
            }
            Stmt::Loop(body) => {
                self.write_indent();
                self.output.push_str("loop ");
                self.gen_block(body);
            }
            Stmt::Break(expr) => {
                self.write_indent();
                if let Some(e) = expr {
                    write!(self.output, "break ").unwrap();
                    self.gen_expr(e);
                    self.output.push_str(";\n");
                } else {
                    self.output.push_str("break;\n");
                }
            }
            Stmt::Continue => {
                self.writeln("continue;");
            }
            Stmt::Match { expr, arms } => {
                self.write_indent();
                self.output.push_str("match ");
                self.gen_expr(expr);
                self.output.push_str(" {\n");
                self.indent += 1;

                for arm in arms {
                    self.write_indent();
                    let pat = self.pattern_str(&arm.pattern);
                    write!(self.output, "{} => ", pat).unwrap();
                    self.gen_expr(&arm.body);
                    self.output.push_str(",\n");
                }

                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {

                self.writeln("{");
                self.indent += 1;
                self.writeln(&format!("let _ruva_result = (|| -> Result<(), String> {{"));
                self.indent += 1;


                for stmt in &try_body.stmts {
                    self.gen_stmt(stmt);
                }

                self.indent -= 1;
                self.writeln("})();");
                self.writeln(&format!("if let Err({}) = _ruva_result {{", catch_param));
                self.indent += 1;
                self.gen_block(catch_body);
                self.indent -= 1;
                self.writeln("}");
                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::Block(block) => {
                self.gen_block(block);
            }
            Stmt::Unsafe(block) => {
                self.writeln("unsafe {");
                self.indent += 1;
                self.gen_block(block);
                self.indent -= 1;
                self.writeln("}");
            }
        }
    }



    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "{}", n).unwrap(),
            Expr::Float(f) => {

                let s = format!("{}", f);
                if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                    write!(self.output, "{}.0", s).unwrap();
                } else {
                    write!(self.output, "{}", s).unwrap();
                }
            }
            Expr::Str(s) => {
                self.output.push('"');
                self.output.push_str(&Self::escape_rust_string(s));
                self.output.push('"');
            }
            Expr::Char(c) => {
                self.output.push('\'');
                self.output.push_str(&Self::escape_rust_char(*c));
                self.output.push('\'');
            }
            Expr::Bool(b) => write!(self.output, "{}", b).unwrap(),
            Expr::Null => self.output.push_str("None"),
            Expr::Self_ => self.output.push_str("self"),
            Expr::Ident(name) => self.output.push_str(name),

            Expr::Path(path) => {
                let s = path.join("::");
                self.output.push_str(&s);
            }

            Expr::Array(elements) => {
                self.output.push('[');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                self.output.push(']');
            }

            Expr::Tuple(elements) => {
                self.output.push('(');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                if elements.len() == 1 {
                    self.output.push(',');
                }
                self.output.push(')');
            }

            Expr::Range { start, end, inclusive } => {
                self.output.push('(');
                self.gen_expr(start);
                if *inclusive {
                    self.output.push_str("..=");
                } else {
                    self.output.push_str("..");
                }
                self.gen_expr(end);
                self.output.push(')');
            }

            Expr::Binary { op, left, right } => {
                self.output.push('(');
                self.gen_expr(left);
                write!(self.output, " {} ", op).unwrap();
                self.gen_expr(right);
                self.output.push(')');
            }

            Expr::Unary { op, expr } => {
                match op {
                    UnaryOp::Neg => self.output.push('-'),
                    UnaryOp::Not => self.output.push('!'),
                    UnaryOp::Deref => self.output.push('*'),
                }
                self.gen_expr(expr);
            }

            Expr::Assign { target, value } => {
                self.gen_expr(target);
                self.output.push_str(" = ");
                self.gen_expr(value);
            }

            Expr::CompoundAssign { op, target, value } => {
                self.gen_expr(target);
                write!(self.output, " {}= ", op).unwrap();
                self.gen_expr(value);
            }

            Expr::Call { function, args } => {
                self.gen_expr(function);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::MethodCall { object, method, args } => {
                self.gen_expr(object);
                self.output.push('.');
                self.output.push_str(method);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::Field { object, field } => {
                self.gen_expr(object);
                self.output.push('.');
                self.output.push_str(field);
            }

            Expr::Index { object, index } => {



                self.gen_expr(object);
                self.output.push('[');
                self.gen_expr(index);
                self.output.push(']');
            }

            Expr::Closure { params, return_type, body } => {
                self.output.push('|');
                for (i, p) in params.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    for _ in 0..p.ref_count { self.output.push('&'); }
                    if p.is_mut { self.output.push_str("mut "); }
                    self.output.push_str(&p.name);
                    if let Some(ref ty) = p.ty {
                        let ty_str = self.type_str(ty);
                        write!(self.output, ": {}", ty_str).unwrap();
                    }
                }
                self.output.push('|');
                if let Some(ref ret) = return_type {
                    let ret_str = self.type_str(ret);
                    write!(self.output, " -> {}", ret_str).unwrap();
                }
                self.output.push(' ');
                self.gen_expr(body);
            }

            Expr::Block(block) => {
                self.gen_block(block);
            }

            Expr::Loop(body) => {
                self.output.push_str("loop ");
                self.gen_block(body);
            }
            Expr::UnsafeBlock(body) => {
                self.writeln("unsafe {");
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.writeln("}");
            }
            Expr::Sizeof(ty) => {
                let ty_str = self.type_str(ty);
                write!(self.output, "std::mem::size_of::<{}>()", ty_str).unwrap();
            }
            Expr::Offsetof { struct_type, field } => {
                write!(self.output, "std::mem::offset_of!({}, {})", struct_type, field).unwrap();
            }
            Expr::NullPtr => {
                write!(self.output, "std::ptr::null_mut()").unwrap();
            }

            Expr::FString(parts) => {

                let mut fmt_str = String::new();
                let mut fargs: Vec<&Expr> = Vec::new();
                for part in parts {
                    match part {
                        crate::ast::FStringPart::Text(text) => {
                            let escaped = Self::escape_rust_format_str(text);
                            fmt_str.push_str(&escaped.replace('{', "{{").replace('}', "}}"));
                        }
                        crate::ast::FStringPart::Expr(expr) => {
                            fmt_str.push_str("{}" );
                            fargs.push(expr);
                        }
                    }
                }
                self.output.push_str("format!(\"");
                self.output.push_str(&fmt_str);
                self.output.push_str("\"");
                for arg in &fargs {
                    self.output.push_str(", ");
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::OptionalChaining { object, field } => {

                self.gen_expr(object);
                write!(self.output, ".as_ref().map(|o| o.{}.clone())", field).unwrap();
            }

            Expr::NullCoalesce { left, right } => {

                self.gen_expr(left);
                self.output.push_str(".unwrap_or_else(|| ");
                self.gen_expr(right);
                self.output.push(')');
            }

            Expr::Assert { condition, message } => {
                self.output.push_str("assert!(");
                self.gen_expr(condition);
                if let Some(ref msg) = message {
                    self.output.push_str(", ");
                    self.gen_expr(msg);
                }
                self.output.push(')');
            }

            Expr::AssertEq { left, right, message } => {
                self.output.push_str("assert_eq!(");
                self.gen_expr(left);
                self.output.push_str(", ");
                self.gen_expr(right);
                if let Some(ref msg) = message {
                    self.output.push_str(", ");
                    self.gen_expr(msg);
                }
                self.output.push(')');
            }

            Expr::AssertNe { left, right, message } => {
                self.output.push_str("assert_ne!(");
                self.gen_expr(left);
                self.output.push_str(", ");
                self.gen_expr(right);
                if let Some(ref msg) = message {
                    self.output.push_str(", ");
                    self.gen_expr(msg);
                }
                self.output.push(')');
            }

            Expr::TryCatch(tc) => {
                self.gen_try_catch(tc);
            }
            Expr::Throw(th) => {
                self.gen_throw(th);
            }
            Expr::Comptime(ct) => {
                self.gen_comptime(ct);
            }
            Expr::ListComp(lc) => {
                self.gen_list_comp(lc);
            }

            Expr::If { condition, then_body, else_body } => {
                self.output.push_str("if ");
                self.gen_expr(condition);
                self.output.push(' ');
                self.gen_block(then_body);
                if let Some(ref else_expr) = else_body {
                    self.output.push_str(" else ");
                    self.gen_expr(else_expr);
                }
            }

            Expr::Match { expr, arms } => {
                self.output.push_str("match ");
                self.gen_expr(expr);
                self.output.push_str(" {\n");
                self.indent += 1;
                for arm in arms {
                    self.write_indent();
                    let pat = self.pattern_str(&arm.pattern);
                    write!(self.output, "{} => ", pat).unwrap();
                    self.gen_expr(&arm.body);
                    self.output.push_str(",\n");
                }
                self.indent -= 1;
                self.writeln("}");
            }

            Expr::Try(expr) => {
                self.gen_expr(expr);
                self.output.push('?');
            }

            Expr::Cast { expr, ty } => {
                self.gen_expr(expr);
                let ty_str = self.type_str(ty);
                write!(self.output, " as {}", ty_str).unwrap();
            }

            Expr::Macro { name, args, separator } => {
                self.output.push_str(name);
                self.output.push('!');
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        if *separator == ';' {
                            self.output.push_str("; ");
                        } else {
                            self.output.push_str(", ");
                        }
                    }
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::Reference { expr, is_mut } => {
                self.output.push('&');
                if *is_mut {
                    self.output.push_str("mut ");
                }
                self.gen_expr(expr);
            }

            Expr::Deref(expr) => {
                self.output.push('*');
                self.gen_expr(expr);
            }

            Expr::Move(expr) => {
                self.output.push_str("move ");
                self.gen_expr(expr);
            }

            Expr::VecLit(elements) => {
                self.output.push_str("vec!");
                self.output.push('[');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                self.output.push(']');
            }

            Expr::StructLiteral { name, fields } => {

                if matches!(name.as_ref(), Expr::Self_) {
                    self.output.push_str("Self");
                } else {
                    self.gen_expr(name);
                }
                self.output.push_str(" {");
                for (i, (field_name, value)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.output.push_str(field_name);
                    self.output.push_str(": ");
                    self.gen_expr(value);
                }
                self.output.push_str("}");
            }
        }
    }



    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat {
            Pattern::Wildcard => "_".to_string(),
            Pattern::Ident(name) => name.clone(),
            Pattern::Literal(expr) => {
                self.gen_expr_to_string(expr)
            }
            Pattern::Tuple(patterns) => {
                let inner: Vec<String> = patterns.iter().map(|p| self.pattern_str(p)).collect();
                format!("({})", inner.join(", "))
            }
            Pattern::Enum { path, fields } => {
                let path_str = path.join("::");
                if fields.is_empty() {
                    path_str
                } else {
                    let field_strs: Vec<String> = fields.iter().map(|f| self.pattern_str(f)).collect();
                    format!("{}({})", path_str, field_strs.join(", "))
                }
            }
            Pattern::Struct { path, fields } => {
                let path_str = path.join("::");
                let field_strs: Vec<String> = fields.iter().map(|(name, pat)| {
                    let pat_str = self.pattern_str(pat);
                    if name == &pat_str {
                        name.clone()
                    } else {
                        format!("{}: {}", name, pat_str)
                    }
                }).collect();
                format!("{} {{ {} }}", path_str, field_strs.join(", "))
            }
            Pattern::Range { start, end, inclusive } => {
                let s = self.gen_expr_to_string(start);
                let e = self.gen_expr_to_string(end);
                if *inclusive {
                    format!("{}..={}", s, e)
                } else {
                    format!("{}..{}", s, e)
                }
            }
            Pattern::Or(patterns) => {
                let inner: Vec<String> = patterns.iter().map(|p| self.pattern_str(p)).collect();
                inner.join(" | ")
            }
            Pattern::Reference(inner) => {
                format!("&{}", self.pattern_str(inner))
            }
            Pattern::Mut(name) => {
                format!("mut {}", name)
            }
        }
    }



    fn type_str(&mut self, ty: &Type) -> String {
        match ty {
            Type::Name(name) => name.clone(),
            Type::Path(path) => path.join("::"),
            Type::Reference { inner, is_mut } => {
                let mut_str = if *is_mut { "mut " } else { "" };
                format!("&{}{}", mut_str, self.type_str(inner))
            }
            Type::Slice(inner) => {
                format!("[{}]", self.type_str(inner))
            }
            Type::Array { inner, size } => {
                if let Some(s) = size {
                    let size_str = self.gen_expr_to_string(s);
                    format!("[{}; {}]", self.type_str(inner), size_str)
                } else {
                    format!("[{}]", self.type_str(inner))
                }
            }
            Type::Tuple(types) => {
                let inner: Vec<String> = types.iter().map(|t| self.type_str(t)).collect();
                if inner.len() == 1 {
                    format!("({},)", inner[0])
                } else {
                    format!("({})", inner.join(", "))
                }
            }
            Type::Generic { name, args } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.type_str(a)).collect();
                format!("{}<{}>", name, arg_strs.join(", "))
            }
            Type::Function { params, return_type } => {
                let param_strs: Vec<String> = params.iter().map(|p| self.type_str(p)).collect();
                format!("fn({}) -> {}", param_strs.join(", "), self.type_str(return_type))
            }
            Type::Unit => "()".to_string(),
            Type::Never => "!".to_string(),
            Type::SelfType => "Self".to_string(),
            Type::RawPointer { inner, is_mut } => {
                if *is_mut {
                    format!("*mut {}", self.type_str(inner))
                } else {
                    format!("*const {}", self.type_str(inner))
                }
            }
        }
    }


    fn write(&mut self, s: &str) {
        self.output.push_str(s);
    }


    fn gen_expr_to_string(&mut self, expr: &Expr) -> String {
        let saved_len = self.output.len();
        self.gen_expr(expr);
        let result = self.output[saved_len..].to_string();
        self.output.truncate(saved_len);
        result
    }



    fn gen_interface(&mut self, iface: &InterfaceDef) {

        let vis = if iface.is_pub { "pub " } else { "" };
        self.writeln(&format!("{}trait {} {{", vis, iface.name));
        self.indent += 1;
        for method in &iface.methods {
            let params: Vec<String> = method.params.iter().map(|p| {
                format!("{}: {}", p.name, self.type_str(&p.ty))
            }).collect();
            let ret = match &method.return_type {
                Some(t) => format!(" -> {}", self.type_str(t)),
                None => String::new(),
            };
            if let Some(ref body) = method.default_body {
                self.writeln(&format!("fn {}({}){} {{", method.name, params.join(", "), ret));
                self.indent += 1;
                for stmt in &body.stmts {
                    self.gen_stmt(stmt);
                }
                if let Some(ref expr) = body.expr {
                    self.write_indent();
                    self.gen_expr(expr);
                    self.output.push('\n');
                }
                self.indent -= 1;
                self.writeln("}");
            } else {
                self.writeln(&format!("fn {}({}){};", method.name, params.join(", "), ret));
            }
        }
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn gen_package(&mut self, pkg: &PackageDef) {

        self.writeln(&format!("// package {}", pkg.path.join(".")));
    }

    fn gen_comptime(&mut self, ct: &ComptimeBlock) {

        self.writeln("const __comptime_result = (|| {");
        self.indent += 1;
        for stmt in &ct.body.stmts {
            self.gen_stmt(stmt);
        }
        if let Some(ref expr) = ct.body.expr {
            self.write_indent();
            self.gen_expr(expr);
            self.output.push('\n');
        }
        self.indent -= 1;
        self.writeln("})();");
    }

    fn gen_decorated(&mut self, dec: &DecoratedDef) {
        for decorator in &dec.decorators {
            self.write_indent();
            self.output.push('#');
            self.gen_expr(decorator);
            self.output.push('\n');
        }
        self.gen_item(&dec.definition);
    }

    fn gen_try_catch(&mut self, tc: &TryCatchExpr) {

        self.writeln("match (|| {");
        self.indent += 1;
        for stmt in &tc.try_body.stmts {
            self.gen_stmt(stmt);
        }
        if let Some(ref expr) = tc.try_body.expr {
            self.write_indent();
            self.gen_expr(expr);
            self.output.push('\n');
        }
        self.indent -= 1;
        self.writeln("})() {");
        self.indent += 1;
        self.writeln("Ok(val) => val,");
        self.writeln("Err(e) => {");
        self.indent += 1;
        for clause in &tc.catch_clauses {
            if let Some(ref var_name) = clause.var_name {
                self.writeln(&format!("let {} = e;", var_name));
            }
            for stmt in &clause.body.stmts {
                self.gen_stmt(stmt);
            }
            if let Some(ref expr) = clause.body.expr {
                self.write_indent();
                self.gen_expr(expr);
                self.output.push('\n');
            }
        }
        self.indent -= 1;
        self.writeln("}");
        self.indent -= 1;
        self.writeln("}");
    }

    fn gen_throw(&mut self, th: &ThrowExpr) {
        self.output.push_str("return Err(");
        self.gen_expr(&th.value);
        self.output.push_str(".into())");
    }

    fn gen_list_comp(&mut self, lc: &ListCompExpr) {

        self.output.push_str("(");
        self.gen_expr(&lc.iterable);
        self.output.push_str(".iter()");
        if let Some(ref cond) = lc.condition {
            self.output.push_str(".filter(|&");
            self.output.push_str(&lc.variable);
            self.output.push_str("| ");
            self.gen_expr(cond);
            self.output.push_str(")");
        }
        self.output.push_str(".map(|");
        self.output.push_str(&lc.variable);
        self.output.push_str("| ");
        self.gen_expr(&lc.element);
        self.output.push_str(").collect::<Vec<_>>())");
    }





    fn escape_rust_string(s: &str) -> String {
        let mut out = String::with_capacity(s.len() * 2);
        for c in s.chars() {
            match c {
                '\u{005c}'  => out.push_str("\\\\"),
                '"' => out.push_str("\\\""),
                '\n' => out.push_str("\\n"),
                '\r' => out.push_str("\\r"),
                '\t' => out.push_str("\\t"),
                '\0' => out.push_str("\\0"),
                c if c.is_control() => {
                    write!(out, "\\x{:02x}", c as u32).unwrap();
                }
                _ => out.push(c),
            }
        }
        out
    }


    fn escape_rust_char(c: char) -> String {
        match c {
            '\u{005c}'  => "\\\\".to_string(),
            '\u{0027}'  => "\\'".to_string(),
            '\n' => "\\n".to_string(),
            '\r' => "\\r".to_string(),
            '\t' => "\\t".to_string(),
            '\0' => "\\0".to_string(),
            c if c.is_control() => format!("\\x{:02x}", c as u32),
            _ => c.to_string(),
        }
    }



    fn escape_rust_format_str(s: &str) -> String {
        let mut out = String::with_capacity(s.len() * 2);
        for c in s.chars() {
            match c {
                '\u{005c}'  => out.push_str("\\\\"),
                '"' => out.push_str("\\\""),
                _ => out.push(c),
            }
        }
        out
    }
}

impl CodeGenerator for CodeGen {
    fn generate(&mut self, program: &Program) -> String {
        self.generate_rust(program)
    }

    fn target_name(&self) -> &str {
        "rust"
    }

    fn file_extension(&self) -> &str {
        ".rs"
    }
}

