use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

pub struct LuaCodeGen { output: String, indent: usize }

impl LuaCodeGen {
    pub fn new() -> Self { Self { output: String::with_capacity(4096), indent: 0 } }
    fn write_indent(&mut self) { for _ in 0..self.indent { self.output.push_str("    "); } }
    fn writeln(&mut self, s: &str) { self.write_indent(); writeln!(self.output, "{}", s).unwrap(); }
    fn write(&mut self, s: &str) { self.output.push_str(s); }

    pub fn generate_lua(&mut self, program: &Program) -> String {
        self.writeln("-- Generated by the Ruva transpiler (Lua backend) — do not edit");
        self.writeln("");
        for item in &program.items { self.gen_item(item); }
        std::mem::take(&mut self.output)
    }

    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Enum(e) => self.gen_enum(e),
            Item::Import(imp) => self.gen_import(imp),
            _ => self.writeln("-- Unsupported item"),
        }
    }

    fn gen_function(&mut self, f: &FunctionDef) {
        let params: Vec<String> = f.params.iter().map(|p| p.name.clone()).collect();
        self.writeln(&format!("function {}({})", f.name, params.join(", ")));
        self.indent += 1; self.gen_block(&f.body); self.indent -= 1; self.writeln("end"); self.writeln("");
    }

    fn gen_struct(&mut self, s: &StructDef) {
        self.writeln(&format!("-- struct {}", s.name));
        self.writeln(&format!("function {}({})", s.name, s.fields.iter().map(|f| f.name.clone()).collect::<Vec<_>>().join(", ")));
        self.indent += 1;
        self.writeln("local self = {}");
        for _f in &s.fields { }
        self.writeln("return self");
        self.indent -= 1; self.writeln("end"); self.writeln("");
    }

    fn gen_enum(&mut self, e: &EnumDef) {
        self.writeln(&format!("-- enum {}", e.name));
        self.writeln(&format!("{} = {{", e.name));
        self.indent += 1;
        for v in &e.variants { self.writeln(&format!("{} = \"{}\",", v.name, v.name)); }
        self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_import(&mut self, imp: &ImportDef) {
        let name = imp.path.split("::").last().unwrap_or("");
        self.writeln(&format!("local {} = require(\"{}\")", name, imp.path.replace("::", ".")));
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts { self.gen_stmt(stmt); }
        if let Some(ref expr) = block.expr { self.write_indent(); self.gen_expr(expr); self.output.push('\n'); }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, is_mut, value, .. } => {
                let kw = if *is_mut { "local" } else { "local" };
                self.write_indent(); let _p = self.pattern_str(pattern); write!(self.output, "{} {} = ", kw, _p).unwrap();
                self.gen_expr(value); self.output.push('\n');
            }
            Stmt::Expr(e) => { self.write_indent(); self.gen_expr(e); self.output.push('\n'); }
            Stmt::Return(e) => { self.write_indent(); if let Some(e) = e { write!(self.output, "return ").unwrap(); self.gen_expr(e); self.output.push('\n'); } else { self.output.push_str("return\n"); } }
            Stmt::If { condition, then_body, else_body } => {
                self.write("if "); self.gen_expr(condition); self.output.push_str(" then\n"); self.indent += 1; self.gen_block(then_body); self.indent -= 1;
                if let Some(ek) = else_body { match ek { ElseKind::If(c, b) => { self.write_indent(); self.write("elseif "); self.gen_expr(c); self.output.push_str(" then\n"); self.indent += 1; self.gen_block(b); self.indent -= 1; } ElseKind::Else(b) => { self.writeln("else"); self.indent += 1; self.gen_block(b); self.indent -= 1; } } }
                self.writeln("end");
            }
            Stmt::For { pattern, iterable, body } => {
                self.write_indent(); let _p = self.pattern_str(pattern); write!(self.output, "for _, {} in ipairs(", _p).unwrap(); self.gen_expr(iterable);
                self.output.push_str(") do\n"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("end");
            }
            Stmt::While { condition, body } => { self.write_indent(); self.output.push_str("while "); self.gen_expr(condition); self.output.push_str(" do\n"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("end"); }
            Stmt::Loop(body) => { self.writeln("while true do"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("end"); }
            Stmt::Break(_) => { self.writeln("break"); }
            Stmt::Continue => { self.writeln("goto continue"); }
            Stmt::Match { .. } => { self.writeln("-- match not supported in Lua"); }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {
                self.writeln("local ok, err = pcall(function()");
                self.indent += 1; self.gen_block(try_body); self.indent -= 1;
                self.writeln("end)");
                self.writeln(&format!("if not ok then local {} = err", catch_param));
                self.indent += 1; self.gen_block(catch_body); self.indent -= 1; self.writeln("end");
            }
            Stmt::Block(b) => self.gen_block(b),
            Stmt::WhileLet { pattern, value, body } => {
                self.gen_stmt(&Stmt::While { condition: value.clone(), body: body.clone() });
            }
            Stmt::Unsafe(b) => self.gen_block(b),
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "{}", n).unwrap(),
            Expr::Float(f) => write!(self.output, "{}", f).unwrap(),
            Expr::Str(s) => write!(self.output, "\"{}\"", s).unwrap(),
            Expr::Bool(b) => { if *b { self.output.push_str("true"); } else { self.output.push_str("false"); } }
            Expr::Null => self.output.push_str("nil"),
            Expr::Self_ => self.output.push_str("self"),
            Expr::Ident(n) => self.output.push_str(n),
            Expr::Binary { op, left, right } => { self.output.push('('); self.gen_expr(left); write!(self.output, " {} ", op).unwrap(); self.gen_expr(right); self.output.push(')'); }
            Expr::Unary { op, expr } => { match op { UnaryOp::Neg => self.output.push('-'), UnaryOp::Not => self.output.push_str("not "), _ => {} }; self.gen_expr(expr); }
            Expr::Assign { target, value } => { self.gen_expr(target); self.output.push_str(" = "); self.gen_expr(value); }
            Expr::Call { function, args } => { self.gen_expr(function); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::MethodCall { object, method, args } => { self.gen_expr(object); self.output.push(':'); self.output.push_str(method); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::Field { object, field } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(field); }
            Expr::Index { object, index } => { self.gen_expr(object); self.output.push('['); self.gen_expr(index); self.output.push(']'); }
            Expr::Macro { name, args, separator: _ } => {
                match name.as_str() {
                    "println" => { self.output.push_str("print("); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                    _ => { self.output.push_str(name); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                }
            }
            Expr::FString(parts) => { self.output.push_str("string.format(\""); for p in parts { match p { FStringPart::Text(t) => self.output.push_str(&t.replace('{', "%s")), FStringPart::Expr(e) => { self.output.push_str("\", "); self.gen_expr(e); self.output.push_str(", string.format(\""); } } } self.output.push_str("\")"); }
            _ => self.output.push_str("nil"),
        }
    }

    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat { Pattern::Wildcard => "_".to_string(), Pattern::Ident(n) => n.clone(), Pattern::Literal(e) => self.gen_expr_to_string(e), _ => "_".to_string() }
    }

    fn gen_expr_to_string(&mut self, expr: &Expr) -> String { let s = self.output.len(); self.gen_expr(expr); let r = self.output[s..].to_string(); self.output.truncate(s); r }
}

impl CodeGenerator for LuaCodeGen {
    fn generate(&mut self, program: &Program) -> String { self.generate_lua(program) }
    fn target_name(&self) -> &str { "lua" }
    fn file_extension(&self) -> &str { ".lua" }
}
