use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

pub struct RubyCodeGen { output: String, indent: usize }

impl RubyCodeGen {
    pub fn new() -> Self { Self { output: String::with_capacity(4096), indent: 0 } }
    fn write_indent(&mut self) { for _ in 0..self.indent { self.output.push_str("    "); } }
    fn writeln(&mut self, s: &str) { self.write_indent(); writeln!(self.output, "{}", s).unwrap(); }
    fn write(&mut self, s: &str) { self.output.push_str(s); }

    pub fn generate_ruby(&mut self, program: &Program) -> String {
        self.writeln("# Generated by the Ruva transpiler (Ruby backend) — do not edit");
        self.writeln("");
        for item in &program.items { self.gen_item(item); }
        std::mem::take(&mut self.output)
    }

    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Class(c) => self.gen_class(c),
            Item::Enum(e) => self.gen_enum(e),
            Item::Trait(t) => self.gen_trait(t),
            Item::Import(imp) => self.gen_import(imp),
            _ => self.writeln("# Unsupported item"),
        }
    }

    fn gen_function(&mut self, f: &FunctionDef) {
        let def = if f.is_pub { "def" } else { "def" };
        let params: Vec<String> = f.params.iter().map(|p| format!("${}", p.name)).collect();
        self.writeln(&format!("{} {}({})", def, f.name, params.join(", ")));
        self.indent += 1; self.gen_block(&f.body); self.indent -= 1; self.writeln("end"); self.writeln("");
    }

    fn gen_struct(&mut self, s: &StructDef) {
        self.writeln(&format!("Struct.new(:{}) do", s.fields.iter().map(|f| f.name.clone()).collect::<Vec<_>>().join(", :")));
        self.indent += 1;
        self.writeln(&format!("def initialize({})", s.fields.iter().map(|f| format!("${}", f.name)).collect::<Vec<_>>().join(", ")));
        self.indent += 1;
        for f in &s.fields { self.writeln(&format!("@{} = ${}", f.name, f.name)); }
        self.indent -= 1; self.writeln("end");
        self.indent -= 1; self.writeln("end"); self.writeln("");
    }

    fn gen_class(&mut self, c: &ClassDef) {
        self.writeln(&format!("class {}", c.name));
        self.indent += 1;
        if !c.fields.is_empty() {
            let params: Vec<String> = c.fields.iter().map(|f| format!("${}", f.name)).collect();
            self.writeln(&format!("def initialize({})", params.join(", ")));
            self.indent += 1;
            for f in &c.fields { self.writeln(&format!("@{} = ${}", f.name, f.name)); }
            self.indent -= 1; self.writeln("end");
            self.writeln("");
            // attr_accessors
            for f in &c.fields {
                let acc = if f.is_pub { "attr_accessor" } else { "attr_reader" };
                self.writeln(&format!("{} :{}", acc, f.name));
            }
        }
        for m in &c.methods { self.gen_function(m); }
        self.indent -= 1; self.writeln("end"); self.writeln("");
    }

    fn gen_enum(&mut self, e: &EnumDef) {
        self.writeln(&format!("module {}", e.name));
        self.indent += 1;
        for v in &e.variants { self.writeln(&format!("{} = :{}", v.name, v.name)); }
        self.indent -= 1; self.writeln("end"); self.writeln("");
    }

    fn gen_trait(&mut self, t: &TraitDef) {
        self.writeln(&format!("module {}Module", t.name));
        self.indent += 1;
        for m in &t.methods {
            let params: Vec<String> = m.params.iter().map(|p| format!("${}", p.name)).collect();
            self.writeln(&format!("def {}({})", m.name, params.join(", ")));
            self.indent += 1; self.writeln("raise NotImplementedError"); self.indent -= 1; self.writeln("end");
        }
        self.indent -= 1; self.writeln("end"); self.writeln("");
    }

    fn gen_import(&mut self, imp: &ImportDef) { self.writeln(&format!("require \"{}\"", imp.path.replace("::", "/").to_lowercase())); }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts { self.gen_stmt(stmt); }
        if let Some(ref expr) = block.expr { self.write_indent(); self.gen_expr(expr); self.output.push('\n'); }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, is_mut, value, .. } => {
                let sigil = if *is_mut { "@" } else { "@" };
                self.write_indent(); let _p = self.pattern_str(pattern); write!(self.output, "{}{} = ", sigil, _p).unwrap();
                self.gen_expr(value); self.output.push('\n');
            }
            Stmt::Expr(e) => { self.write_indent(); self.gen_expr(e); self.output.push('\n'); }
            Stmt::Return(e) => { self.write_indent(); if let Some(e) = e { write!(self.output, "return ").unwrap(); self.gen_expr(e); self.output.push('\n'); } else { self.output.push_str("return\n"); } }
            Stmt::If { condition, then_body, else_body } => {
                self.write("if "); self.gen_expr(condition); self.output.push('\n'); self.indent += 1; self.gen_block(then_body); self.indent -= 1;
                if let Some(ek) = else_body { match ek { ElseKind::If(c, b) => { self.write_indent(); self.write("elsif "); self.gen_expr(c); self.output.push('\n'); self.indent += 1; self.gen_block(b); self.indent -= 1; } ElseKind::Else(b) => { self.writeln("else"); self.indent += 1; self.gen_block(b); self.indent -= 1; } } }
                self.writeln("end");
            }
            Stmt::For { pattern, iterable, body } => {
                self.write_indent(); let _p = self.pattern_str(pattern); write!(self.output, "for {} in ", _p).unwrap(); self.gen_expr(iterable);
                self.output.push('\n'); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("end");
            }
            Stmt::While { condition, body } => { self.write_indent(); self.output.push_str("while "); self.gen_expr(condition); self.output.push('\n'); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("end"); }
            Stmt::Loop(body) => { self.writeln("loop do"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("end"); }
            Stmt::Break(_) => { self.writeln("break"); }
            Stmt::Continue => { self.writeln("next"); }
            Stmt::Match { .. } => { self.writeln("# case/when"); }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {
                self.writeln("begin"); self.indent += 1; self.gen_block(try_body); self.indent -= 1;
                self.write_indent(); self.writeln(&format!("rescue => {}", catch_param));
                self.indent += 1; self.gen_block(catch_body); self.indent -= 1; self.writeln("end");
            }
            Stmt::Block(b) => self.gen_block(b),
            Stmt::WhileLet { pattern, value, body } => {
                self.gen_stmt(&Stmt::While { condition: value.clone(), body: body.clone() });
            }
            Stmt::Unsafe(b) => self.gen_block(b),
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "{}", n).unwrap(),
            Expr::Float(f) => write!(self.output, "{}", f).unwrap(),
            Expr::Str(s) => write!(self.output, "\"{}\"", s).unwrap(),
            Expr::Bool(b) => { if *b { self.output.push_str("true"); } else { self.output.push_str("false"); } }
            Expr::Null => self.output.push_str("nil"),
            Expr::Self_ => self.output.push_str("self"),
            Expr::Ident(n) => self.output.push_str(n),
            Expr::Binary { op, left, right } => { self.output.push('('); self.gen_expr(left); write!(self.output, " {} ", op).unwrap(); self.gen_expr(right); self.output.push(')'); }
            Expr::Unary { op, expr } => { match op { UnaryOp::Neg => self.output.push('-'), UnaryOp::Not => self.output.push_str("!"), _ => {} }; self.gen_expr(expr); }
            Expr::Assign { target, value } => { self.gen_expr(target); self.output.push_str(" = "); self.gen_expr(value); }
            Expr::Call { function, args } => { self.gen_expr(function); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::MethodCall { object, method, args } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(method); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::Field { object, field } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(field); }
            Expr::Index { object, index } => { self.gen_expr(object); self.output.push('['); self.gen_expr(index); self.output.push(']'); }
            Expr::Macro { name, args } => {
                match name.as_str() {
                    "println" => { self.output.push_str("puts("); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                    _ => { self.output.push_str(name); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                }
            }
            Expr::FString(parts) => { self.output.push('"'); for p in parts { match p { FStringPart::Text(t) => self.output.push_str(t), FStringPart::Expr(e) => { self.output.push_str("#{"); self.gen_expr(e); self.output.push('}'); } } } self.output.push('"'); }
            _ => self.output.push_str("nil"),
        }
    }

    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat { Pattern::Wildcard => "_".to_string(), Pattern::Ident(n) => format!("${}", n), Pattern::Literal(e) => self.gen_expr_to_string(e), _ => "_".to_string() }
    }

    fn gen_expr_to_string(&mut self, expr: &Expr) -> String { let s = self.output.len(); self.gen_expr(expr); let r = self.output[s..].to_string(); self.output.truncate(s); r }
}

impl CodeGenerator for RubyCodeGen {
    fn generate(&mut self, program: &Program) -> String { self.generate_ruby(program) }
    fn target_name(&self) -> &str { "ruby" }
    fn file_extension(&self) -> &str { ".rb" }
}
