use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

/// Zig code generator — transpiles Ruva AST to Zig source code.
///
/// Zig is a systems language with manual memory management, comptime,
/// and C-level performance. Ruva's struct/class model maps naturally.
pub struct ZigCodeGen {
    output: String,
    indent: usize,
}

impl ZigCodeGen {
    pub fn new() -> Self {
        Self {
            output: String::with_capacity(4096),
            indent: 0,
        }
    }

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        writeln!(self.output, "{}", s).unwrap();
    }

    fn write(&mut self, s: &str) {
        self.output.push_str(s);
    }

    // ─── Top-level generation ───────────────────────────────────────────

    pub fn generate_zig(&mut self, program: &Program) -> String {
        self.writeln("// Generated by the Ruva transpiler (Zig backend) — do not edit");
        self.writeln("const std = @import(\"std\");");
        self.writeln("");

        for item in &program.items {
            self.gen_item(item);
        }

        std::mem::take(&mut self.output)
    }

    // ─── Items ──────────────────────────────────────────────────────────

    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Class(c) => self.gen_class(c),
            Item::Enum(e) => self.gen_enum(e),
            Item::Impl(imp) => self.gen_impl(imp),
            Item::Trait(t) => self.gen_trait(t),
            Item::TypeAlias(ta) => self.gen_type_alias(ta),
            Item::Import(imp) => self.gen_import(imp),
            Item::Use(u) => self.gen_use(u),
            Item::Attribute(attr) => self.gen_attribute(attr),
            Item::Module(m) => self.gen_module(m),
            Item::ExternBlock(eb) => self.gen_extern_block(eb),
            _ => self.writeln("// Unsupported item"),
        }
    }

    // ─── Functions ──────────────────────────────────────────────────────

    fn gen_function(&mut self, f: &FunctionDef) {
        let vis = if f.is_pub { "pub " } else { "" };

        // Generics (Zig uses comptime parameters)
        let generics = if f.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = f.generics.iter().map(|g| {
                format!("comptime {}: type", g.name)
            }).collect();
            format!("{} ", params.join(", "))
        };

        // Parameters
        let params: Vec<String> = f.params.iter().map(|p| {
            if let Type::SelfType = &p.ty {
                // In Zig, self is passed as the first parameter
                if p.is_ref {
                    if p.is_mut {
                        format!("self: *Self")
                    } else {
                        format!("self: *const Self")
                    }
                } else {
                    format!("self: Self")
                }
            } else {
                let ty = self.type_str(&p.ty);
                if p.is_ref {
                    if p.is_mut {
                        format!("{}: *{}", p.name, ty)
                    } else {
                        format!("{}: *const {}", p.name, ty)
                    }
                } else {
                    format!("{}: {}", p.name, ty)
                }
            }
        }).collect();

        // Return type
        let ret = match &f.return_type {
            Some(ty) => format!(" -> {}", self.type_str(ty)),
            None => String::new(),
        };

        if f.is_test {
            self.writeln("// @test");
        }

        let all_params = if generics.is_empty() {
            params.join(", ")
        } else {
            format!("{}{}", generics, params.join(", "))
        };
        self.writeln(&format!("{}fn {}({}){} {{", vis, f.name, all_params, ret));
        self.indent += 1;
        self.gen_block(&f.body);
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    // ─── Structs ────────────────────────────────────────────────────────

    fn gen_struct(&mut self, s: &StructDef) {
        let vis = if s.is_pub { "pub " } else { "" };

        let generics = if s.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = s.generics.iter().map(|g| {
                format!("comptime {}: type", g.name)
            }).collect();
            format!("[{}]", params.join(", "))
        };

        self.writeln(&format!("{}const {}{} = struct {{", vis, s.name, generics));
        self.indent += 1;

        for field in &s.fields {
            let ty = self.type_str(&field.ty);
            if field.is_pub {
                self.writeln(&format!("pub {}: {},", field.name, ty));
            } else {
                self.writeln(&format!("{}: {},", field.name, ty));
            }
        }

        // Add init function if there are fields
        if !s.fields.is_empty() {
            self.writeln("");
            self.write_indent();
            self.write("pub fn init(");
            let init_params: Vec<String> = s.fields.iter().map(|f| {
                format!("{}: {}", f.name, self.type_str(&f.ty))
            }).collect();
            self.write(&init_params.join(", "));
            self.writeln(") Self {");
            self.indent += 1;
            self.writeln("return Self{");
            self.indent += 1;
            for field in &s.fields {
                self.writeln(&format!(".{} = {},", field.name, field.name));
            }
            self.indent -= 1;
            self.writeln("};");
            self.indent -= 1;
            self.writeln("}");
        }

        self.indent -= 1;
        self.writeln("};");
        self.writeln("");
    }

    // ─── Enums ──────────────────────────────────────────────────────────

    fn gen_enum(&mut self, e: &EnumDef) {
        let vis = if e.is_pub { "pub " } else { "" };

        // Check if any variant has fields (tagged union)
        let has_data = e.variants.iter().any(|v| !v.fields.is_empty());

        if has_data {
            // Tagged union for enums with data
            self.writeln(&format!("{}const {} = union(enum {{", vis, e.name));
            self.indent += 1;

            for variant in &e.variants {
                if variant.fields.is_empty() {
                    self.writeln(&format!("{},", variant.name));
                } else {
                    self.writeln(&format!("{}: struct {{", variant.name));
                    self.indent += 1;
                    for (i, ty) in variant.fields.iter().enumerate() {
                        let ty_str = self.type_str(ty);
                        self.writeln(&format!("field_{}: {},", i, ty_str));
                    }
                    self.indent -= 1;
                    self.writeln("},");
                }
            }

            self.indent -= 1;
            self.writeln("};");
        } else {
            // Simple enum (generics noted as comment)
            self.writeln(&format!("{}const {} = enum {{", vis, e.name));
            self.indent += 1;

            for variant in &e.variants {
                self.writeln(&format!("{},", variant.name));
            }

            self.indent -= 1;
            self.writeln("};");
        }
        self.writeln("");
    }

    // ─── Classes (struct + methods) ─────────────────────────────────────

    fn gen_class(&mut self, c: &ClassDef) {
        let vis = if c.is_pub { "pub " } else { "" };

        let generics = if c.generics.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = c.generics.iter().map(|g| {
                format!("comptime {}: type", g.name)
            }).collect();
            format!("[{}]", params.join(", "))
        };

        self.writeln(&format!("{}const {}{} = struct {{", vis, c.name, generics));
        self.indent += 1;

        for field in &c.fields {
            let ty = self.type_str(&field.ty);
            if field.is_pub {
                self.writeln(&format!("pub {}: {},", field.name, ty));
            } else {
                self.writeln(&format!("{}: {},", field.name, ty));
            }
        }

        // Constructor
        if !c.fields.is_empty() {
            self.writeln("");
            self.write_indent();
            self.write("pub fn init(");
            let init_params: Vec<String> = c.fields.iter().map(|f| {
                format!("{}: {}", f.name, self.type_str(&f.ty))
            }).collect();
            self.write(&init_params.join(", "));
            self.writeln(") Self {");
            self.indent += 1;
            self.writeln("return Self{");
            self.indent += 1;
            for field in &c.fields {
                self.writeln(&format!(".{} = {},", field.name, field.name));
            }
            self.indent -= 1;
            self.writeln("};");
            self.indent -= 1;
            self.writeln("}");
        }

        // Methods
        for method in &c.methods {
            self.writeln("");
            self.gen_function(method);
        }

        self.indent -= 1;
        self.writeln("};");
        self.writeln("");
    }

    // ─── Impl Blocks ────────────────────────────────────────────────────

    fn gen_impl(&mut self, imp: &ImplBlock) {
        // In Zig, impl blocks don't exist — methods are inside the struct.
        // Generate standalone functions with the type as first parameter.
        let self_type = self.type_str(&imp.self_type);

        for method in &imp.methods {
            self.writeln(&format!("// impl {} for {}", method.name, self_type));
            self.gen_function(method);
        }
    }

    // ─── Traits (interface via comptime) ────────────────────────────────

    fn gen_trait(&mut self, t: &TraitDef) {
        self.writeln(&format!("// trait {} — in Zig, enforced via comptime duck-typing", t.name));

        // Generate a namespace with the method signatures as type declarations
        let vis = if t.is_pub { "pub " } else { "" };
        self.writeln(&format!("{}const {} = struct {{", vis, t.name));
        self.indent += 1;

        for method in &t.methods {
            let params: Vec<String> = method.params.iter().map(|p| {
                if let Type::SelfType = &p.ty {
                    "self: anytype".to_string()
                } else {
                    let ty = self.type_str(&p.ty);
                    format!("{}: {}", p.name, ty)
                }
            }).collect();

            let ret = match &method.return_type {
                Some(ty) => format!(" -> {}", self.type_str(ty)),
                None => String::new(),
            };

            if let Some(ref body) = method.default_body {
                self.writeln(&format!("pub fn {}({}){} {{", method.name, params.join(", "), ret));
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.writeln("}");
            } else {
                self.writeln(&format!("pub fn {}({}){};", method.name, params.join(", "), ret));
            }
        }

        self.indent -= 1;
        self.writeln("};");
        self.writeln("");
    }

    // ─── Type Alias ─────────────────────────────────────────────────────

    fn gen_type_alias(&mut self, ta: &TypeAliasDef) {
        let ty = self.type_str(&ta.ty);
        if ta.is_pub {
            self.writeln(&format!("pub const {} = {};", ta.name, ty));
        } else {
            self.writeln(&format!("const {} = {};", ta.name, ty));
        }
        self.writeln("");
    }

    // ─── Imports ────────────────────────────────────────────────────────

    fn gen_import(&mut self, imp: &ImportDef) {
        // Map ruva:: imports to Zig @import
        if imp.path.starts_with("ruva::") {
            let parts: Vec<&str> = imp.path.split("::").collect();
            if let Some(name) = parts.last() {
                self.writeln(&format!("const {} = @import(\"{}\");", name, name));
            }
        } else {
            self.writeln(&format!("// import: {}", imp.path));
        }
    }

    // ─── Attributes ─────────────────────────────────────────────────────

    fn gen_attribute(&mut self, attr: &Attribute) {
        self.writeln(&format!("// @{}", attr.name));
        self.gen_item(&attr.item);
    }

    // ─── Module ─────────────────────────────────────────────────────────

    fn gen_use(&mut self, u: &UseDef) {
        let path_str = u.path.join("::");
        if u.wildcard {
            self.writeln(&format!("// use {}::*", path_str));
        } else if !u.selective.is_empty() {
            let items: Vec<String> = u.selective.iter().map(|item| {
                if let Some(ref alias) = item.alias {
                    format!("{} as {}", item.name, alias)
                } else {
                    item.name.clone()
                }
            }).collect();
            self.writeln(&format!("// use {}::{{{}}}", path_str, items.join(", ")));
        } else if let Some(ref alias) = u.alias {
            self.writeln(&format!("const {} = @import(\"{}\");", alias, u.path.last().unwrap_or(&String::new())));
        } else if let Some(last) = u.path.last() {
            self.writeln(&format!("const {} = @import(\"{}\");", last, last));
        }
    }

    fn gen_module(&mut self, m: &ModDef) {
        if let Some(ref body) = m.body {
            self.writeln(&format!("pub const {} = struct {{", m.name));
            self.indent += 1;
            for item in body {
                self.gen_item(item);
            }
            self.indent -= 1;
            self.writeln("};");
        } else {
            self.writeln(&format!("const {} = @import(\"{}\");", m.name, m.name));
        }
    }

    fn gen_extern_block(&mut self, eb: &ExternBlock) {
        self.writeln(&format!("extern \"{}\" {{", eb.abi));
        self.indent += 1;
        let items: Vec<ExternItem> = eb.items.iter().cloned().collect();
        for item in &items {
            match item {
                ExternItem::Function { is_pub, ref name, ref params, ref return_type } => {
                    let vis = if *is_pub { "pub " } else { "" };
                    let params_str: Vec<String> = params.iter().map(|p| {
                        format!("{}: {}", p.name, self.type_str(&p.ty))
                    }).collect();
                    let ret = match return_type {
                        Some(ref t) => format!(" -> {}", self.type_str(t)),
                        None => String::new(),
                    };
                    self.writeln(&format!("{}fn {}({}){}", vis, name, params_str.join(", "), ret));
                }
                ExternItem::Static { is_pub, is_mut, ref name, ref ty } => {
                    let vis = if *is_pub { "pub " } else { "" };
                    let mutability = if *is_mut { "var " } else { "" };
                    let ty_str = self.type_str(ty);
                    self.writeln(&format!("{}{}{}: {}", vis, mutability, name, ty_str));
                }
                ExternItem::Const { is_pub, ref name, ref ty, value: _ } => {
                    let vis = if *is_pub { "pub " } else { "" };
                    let ty_str = self.type_str(ty);
                    self.writeln(&format!("{}const {}: {}", vis, name, ty_str));
                }
            }
        }
        self.indent -= 1;
        self.writeln("}");
    }

    // ─── Blocks ─────────────────────────────────────────────────────────

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }

        if let Some(ref expr) = block.expr {
            self.write_indent();
            self.gen_expr(expr);
            self.output.push('\n');
        }
    }

    // ─── Statements ─────────────────────────────────────────────────────

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, ty, is_mut, value } => {
                let keyword = if *is_mut { "var" } else { "const" };
                let pat_str = self.pattern_str(pattern);
                let ty_str = match ty {
                    Some(t) => format!(": {}", self.type_str(t)),
                    None => String::new(),
                };
                self.write_indent();
                write!(self.output, "{} {}{}", keyword, pat_str, ty_str).unwrap();
                self.output.push_str(" = ");
                self.gen_expr(value);
                self.output.push_str(";\n");
            }
            Stmt::Expr(expr) => {
                self.write_indent();
                self.gen_expr(expr);
                self.output.push_str(";\n");
            }
            Stmt::Return(expr) => {
                self.write_indent();
                if let Some(e) = expr {
                    write!(self.output, "return ").unwrap();
                    self.gen_expr(e);
                    self.output.push_str(";\n");
                } else {
                    self.output.push_str("return;\n");
                }
            }
            Stmt::If { condition, then_body, else_body } => {
                self.write("if (");
                self.gen_expr(condition);
                self.output.push(')');
                self.output.push(' ');
                self.output.push_str("{\n");
                self.indent += 1;
                self.gen_block(then_body);
                self.indent -= 1;
                self.write_indent();
                self.output.push_str("}");

                if let Some(else_kind) = else_body {
                    match else_kind {
                        ElseKind::If(cond, body) => {
                            self.output.push_str(" else if (");
                            self.gen_expr(cond);
                            self.output.push_str(") {\n");
                            self.indent += 1;
                            self.gen_block(body);
                            self.indent -= 1;
                            self.write_indent();
                            self.output.push('}');
                        }
                        ElseKind::Else(body) => {
                            self.output.push_str(" else {\n");
                            self.indent += 1;
                            self.gen_block(body);
                            self.indent -= 1;
                            self.write_indent();
                            self.output.push('}');
                        }
                    }
                }
                self.output.push('\n');
            }
            Stmt::For { pattern, iterable, body } => {
                // Zig uses `for` with slices
                let pat_str = self.pattern_str(pattern);
                self.write_indent();
                write!(self.output, "for (").unwrap();
                self.gen_expr(iterable);
                write!(self.output, ") |{}| {{", pat_str).unwrap();
                self.output.push('\n');
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
            }
            Stmt::While { condition, body } => {
                self.write_indent();
                self.output.push_str("while (");
                self.gen_expr(condition);
                self.output.push_str(") {\n");
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
            }
            Stmt::WhileLet { pattern, value, body } => {
                // Zig: while with optional unwrapping
                let pat_str = self.pattern_str(pattern);
                self.write_indent();
                self.output.push_str("while (");
                self.gen_expr(value);
                write!(self.output, ") |{}| {{", pat_str).unwrap();
                self.output.push('\n');
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
            }
            Stmt::Loop(body) => {
                self.write_indent();
                self.output.push_str("while (true) {\n");
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
            }
            Stmt::Break(expr) => {
                self.write_indent();
                if let Some(e) = expr {
                    write!(self.output, "break ").unwrap();
                    self.gen_expr(e);
                    self.output.push_str(";\n");
                } else {
                    self.output.push_str("break;\n");
                }
            }
            Stmt::Continue => {
                self.writeln("continue;");
            }
            Stmt::Match { expr, arms } => {
                // Zig: switch statement
                self.write_indent();
                self.output.push_str("switch (");
                self.gen_expr(expr);
                self.output.push_str(") {\n");
                self.indent += 1;

                for arm in arms {
                    self.write_indent();
                    let pat = self.pattern_str(&arm.pattern);
                    write!(self.output, "{} => ", pat).unwrap();
                    self.gen_expr(&arm.body);
                    self.output.push_str(",\n");
                }

                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
            }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {
                // Zig: try/catch with error handling
                self.writeln("{");
                self.indent += 1;
                self.writeln(&format!("const _result = blk: {{"));
                self.indent += 1;
                for stmt in &try_body.stmts {
                    self.gen_stmt(stmt);
                }
                self.writeln("break :blk {};");
                self.indent -= 1;
                self.writeln("};");
                self.writeln(&format!("if (_result) |{}| {{", catch_param));
                self.indent += 1;
                self.gen_block(catch_body);
                self.indent -= 1;
                self.writeln("} else |_| {}");
                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::Block(block) => {
                self.writeln("{");
                self.indent += 1;
                self.gen_block(block);
                self.indent -= 1;
                self.writeln("}");
            }
            Stmt::Unsafe(block) => {
                // Zig doesn't have unsafe blocks — just generate the block
                self.gen_block(block);
            }
        }
    }

    // ─── Expressions ────────────────────────────────────────────────────

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "@intCast({})", n).unwrap(),
            Expr::Float(f) => {
                let s = format!("{}", f);
                if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                    write!(self.output, "@as(f64, {})", s).unwrap();
                } else {
                    write!(self.output, "@as(f64, {})", s).unwrap();
                }
            }
            Expr::Str(s) => write!(self.output, "\"{}\"", s).unwrap(),
            Expr::Char(c) => write!(self.output, "'{}'", c).unwrap(),
            Expr::Bool(b) => {
                if *b {
                    self.output.push_str("true");
                } else {
                    self.output.push_str("false");
                }
            }
            Expr::Null => self.output.push_str("null"),
            Expr::Self_ => self.output.push_str("self"),
            Expr::Ident(name) => self.output.push_str(name),

            Expr::Path(path) => {
                let s = path.join(".");
                self.output.push_str(&s);
            }

            Expr::Array(elements) => {
                self.output.push('[');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                self.output.push(']');
            }

            Expr::Tuple(elements) => {
                // Zig tuples
                self.output.push('.');
                self.output.push('(');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                if elements.len() == 1 {
                    self.output.push(',');
                }
                self.output.push(')');
            }

            Expr::Range { start, end, inclusive } => {
                self.gen_expr(start);
                if *inclusive {
                    self.output.push_str("..=");
                } else {
                    self.output.push_str("..");
                }
                self.gen_expr(end);
            }

            Expr::Binary { op, left, right } => {
                self.output.push('(');
                self.gen_expr(left);
                write!(self.output, " {} ", op).unwrap();
                self.gen_expr(right);
                self.output.push(')');
            }

            Expr::Unary { op, expr } => {
                match op {
                    UnaryOp::Neg => self.output.push('-'),
                    UnaryOp::Not => self.output.push('!'),
                    UnaryOp::Deref => self.output.push('*'),
                }
                self.gen_expr(expr);
            }

            Expr::Assign { target, value } => {
                self.gen_expr(target);
                self.output.push_str(" = ");
                self.gen_expr(value);
            }

            Expr::CompoundAssign { op, target, value } => {
                self.gen_expr(target);
                write!(self.output, " {}= ", op).unwrap();
                self.gen_expr(value);
            }

            Expr::Call { function, args } => {
                self.gen_expr(function);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::MethodCall { object, method, args } => {
                self.gen_expr(object);
                self.output.push_str(".");
                self.output.push_str(method);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::Field { object, field } => {
                self.gen_expr(object);
                self.output.push('.');
                self.output.push_str(field);
            }

            Expr::Index { object, index } => {
                self.gen_expr(object);
                self.output.push('[');
                self.gen_expr(index);
                self.output.push(']');
            }

            Expr::Closure { params, return_type: _, body } => {
                // Zig closures are not first-class; generate a struct with `call`
                self.output.push_str("struct { fn call(");
                for (i, p) in params.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    let ty = p.ty.as_ref().map(|t| self.type_str(t)).unwrap_or_else(|| "anytype".to_string());
                    write!(self.output, "{}: {}", p.name, ty).unwrap();
                }
                self.output.push_str(") void ");
                self.gen_expr(body);
                self.output.push('}');
            }

            Expr::Block(block) => {
                self.writeln("{");
                self.indent += 1;
                self.gen_block(block);
                self.indent -= 1;
                self.write_indent();
                self.writeln("}");
            }

            Expr::Loop(body) => {
                self.output.push_str("while (true) ");
                self.gen_block_expr(body);
            }
            Expr::UnsafeBlock(body) => {
                // Zig doesn't have unsafe — just generate the block
                self.gen_block_expr(body);
            }
            Expr::Sizeof(ty) => {
                let ty_str = self.type_str(ty);
                write!(self.output, "@sizeOf({})", ty_str).unwrap();
            }
            Expr::Offsetof { struct_type, field } => {
                write!(self.output, "@offsetOf({}, \"{}\")", struct_type, field).unwrap();
            }
            Expr::NullPtr => {
                write!(self.output, "@ptrFromInt(0)").unwrap();
            }

            Expr::If { condition, then_body, else_body } => {
                self.output.push_str("if (");
                self.gen_expr(condition);
                self.output.push_str(") ");
                self.gen_block_expr(then_body);
                if let Some(ref else_expr) = else_body {
                    self.output.push_str(" else ");
                    self.gen_expr(else_expr);
                }
            }

            Expr::Match { expr, arms } => {
                self.output.push_str("switch (");
                self.gen_expr(expr);
                self.output.push_str(") {\n");
                self.indent += 1;
                for arm in arms {
                    self.write_indent();
                    let pat = self.pattern_str(&arm.pattern);
                    write!(self.output, "{} => ", pat).unwrap();
                    self.gen_expr(&arm.body);
                    self.output.push_str(",\n");
                }
                self.indent -= 1;
                self.write_indent();
                self.output.push('}');
            }

            Expr::Try(expr) => {
                self.gen_expr(expr);
                self.output.push_str(" catch undefined");
            }

            Expr::Cast { expr, ty } => {
                self.gen_expr(expr);
                let ty_str = self.type_str(ty);
                write!(self.output, " // as {}", ty_str).unwrap();
            }

            Expr::Macro { name, args } => {
                // Map common macros to Zig equivalents
                match name.as_str() {
                    "println" => {
                        // std.debug.print("{s}\n", .{arg})
                        if let Some(first) = args.first() {
                            if let Expr::Str(s) = first {
                                // First arg is the format string
                                self.output.push_str(&format!("std.debug.print(\"{}\\n\", .{{", s));
                                // Remaining args are values
                                for (i, arg) in args.iter().skip(1).enumerate() {
                                    if i > 0 {
                                        self.output.push_str(", ");
                                    }
                                    self.gen_expr(arg);
                                }
                                self.output.push_str("})");
                            } else {
                                // Non-string first arg
                                self.output.push_str("std.debug.print(\"{s}\\n\", .{");
                                for (i, arg) in args.iter().enumerate() {
                                    if i > 0 {
                                        self.output.push_str(", ");
                                    }
                                    self.gen_expr(arg);
                                }
                                self.output.push_str("})");
                            }
                        } else {
                            self.output.push_str("std.debug.print(\"\\n\", .{})");
                        }
                    }
                    "print" => {
                        if let Some(first) = args.first() {
                            if let Expr::Str(s) = first {
                                self.output.push_str(&format!("std.debug.print(\"{}\", .{{", s));
                                for (i, arg) in args.iter().skip(1).enumerate() {
                                    if i > 0 {
                                        self.output.push_str(", ");
                                    }
                                    self.gen_expr(arg);
                                }
                                self.output.push_str("})");
                            } else {
                                self.output.push_str("std.debug.print(\"{s}\", .{");
                                for (i, arg) in args.iter().enumerate() {
                                    if i > 0 {
                                        self.output.push_str(", ");
                                    }
                                    self.gen_expr(arg);
                                }
                                self.output.push_str("})");
                            }
                        }
                    }
                    _ => {
                        self.output.push_str(name);
                        self.output.push('(');
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.output.push(')');
                    }
                }
            }

            Expr::Reference { expr, is_mut } => {
                if *is_mut {
                    self.output.push_str("&");
                } else {
                    self.output.push_str("&");
                }
                self.gen_expr(expr);
            }

            Expr::Deref(expr) => {
                self.output.push('*');
                self.gen_expr(expr);
            }

            Expr::Move(expr) => {
                // Zig has no move semantics — just generate the expression
                self.gen_expr(expr);
            }

            Expr::VecLit(elements) => {
                // Zig: use ArrayList or fixed array
                self.output.push_str("[_]u8{");
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                self.output.push('}');
            }

            Expr::StructLiteral { name, fields } => {
                if matches!(name.as_ref(), Expr::Self_) {
                    self.output.push_str("Self");
                } else {
                    self.gen_expr(name);
                }
                self.output.push_str(" {");
                for (i, (field_name, value)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    write!(self.output, ".{} = ", field_name).unwrap();
                    self.gen_expr(value);
                }
                self.output.push('}');
            }

            Expr::FString(parts) => {
                for part in parts {
                    match part {
                        crate::ast::FStringPart::Text(text) => self.output.push_str(text),
                        crate::ast::FStringPart::Expr(expr) => {
                            self.output.push_str("{}");
                            self.gen_expr(expr);
                        }
                    }
                }
            }
            Expr::OptionalChaining { object, field } => {
                self.gen_expr(object);
                write!(self.output, ".{}", field).unwrap();
            }
            Expr::NullCoalesce { left, right } => {
                self.gen_expr(left);
                self.output.push_str(" orelse ");
                self.gen_expr(right);
            }
            Expr::Assert { condition, .. } => {
                self.output.push_str("assert ");
                self.gen_expr(condition);
            }
            Expr::AssertEq { left, right, .. } => {
                self.output.push_str("assert ");
                self.gen_expr(left);
                self.output.push_str(" == ");
                self.gen_expr(right);
            }
            Expr::AssertNe { left, right, .. } => {
                self.output.push_str("assert ");
                self.gen_expr(left);
                self.output.push_str(" != ");
                self.gen_expr(right);
            }
            _ => self.output.push_str("undefined"),
        }
    }

    fn gen_block_expr(&mut self, block: &Block) {
        self.output.push_str("{\n");
        self.indent += 1;
        self.gen_block(block);
        self.indent -= 1;
        self.write_indent();
        self.output.push_str("}");
    }

    // ─── Patterns ───────────────────────────────────────────────────────

    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat {
            Pattern::Wildcard => "_".to_string(),
            Pattern::Ident(name) => name.clone(),
            Pattern::Literal(expr) => self.gen_expr_to_string(expr),
            Pattern::Tuple(patterns) => {
                let inner: Vec<String> = patterns.iter().map(|p| self.pattern_str(p)).collect();
                format!(".{{ {} }}", inner.join(", "))
            }
            Pattern::Enum { path, fields } => {
                let variant = path.last().cloned().unwrap_or_default();
                if fields.is_empty() {
                    format!(".{}", variant)
                } else {
                    let field_strs: Vec<String> = fields.iter().map(|f| self.pattern_str(f)).collect();
                    format!(".{} {{ .{} }}", variant, field_strs.join(", ."))
                }
            }
            Pattern::Struct { path, fields } => {
                let name = path.last().cloned().unwrap_or_default();
                let field_strs: Vec<String> = fields.iter().map(|(n, p)| {
                    let p_str = self.pattern_str(p);
                    format!(".{} = {}", n, p_str)
                }).collect();
                format!(".{} {{ {} }}", name, field_strs.join(", "))
            }
            Pattern::Range { start, end, inclusive } => {
                let s = self.gen_expr_to_string(start);
                let e = self.gen_expr_to_string(end);
                if *inclusive {
                    format!("{}...={}", s, e)
                } else {
                    format!("{}...{}", s, e)
                }
            }
            Pattern::Or(patterns) => {
                let inner: Vec<String> = patterns.iter().map(|p| self.pattern_str(p)).collect();
                inner.join(" | ")
            }
            Pattern::Reference(inner) => {
                format!("&{}", self.pattern_str(inner))
            }
            Pattern::Mut(name) => {
                format!("mut {}", name)
            }
        }
    }

    // ─── Types ──────────────────────────────────────────────────────────

    fn type_str(&mut self, ty: &Type) -> String {
        match ty {
            Type::Name(name) => {
                // Map Ruva types to Zig types
                match name.as_str() {
                    "i8" => "i8".to_string(),
                    "i16" => "i16".to_string(),
                    "i32" => "i32".to_string(),
                    "i64" => "i64".to_string(),
                    "i128" => "i128".to_string(),
                    "isize" => "isize".to_string(),
                    "u8" => "u8".to_string(),
                    "u16" => "u16".to_string(),
                    "u32" => "u32".to_string(),
                    "u64" => "u64".to_string(),
                    "u128" => "u128".to_string(),
                    "usize" => "usize".to_string(),
                    "f32" => "f32".to_string(),
                    "f64" => "f64".to_string(),
                    "bool" => "bool".to_string(),
                    "char" => "u21".to_string(), // Zig uses u21 for Unicode codepoints
                    "string" => "[]const u8".to_string(),
                    "string!" => "![]const u8".to_string(),
                    "()" => "void".to_string(),
                    "!" => "noreturn".to_string(),
                    _ => name.clone(),
                }
            }
            Type::Path(path) => path.join("."),
            Type::Reference { inner, is_mut } => {
                let inner_str = self.type_str(inner);
                if *is_mut {
                    format!("*{}", inner_str)
                } else {
                    format!("*const {}", inner_str)
                }
            }
            Type::Slice(inner) => {
                format!("[]{}", self.type_str(inner))
            }
            Type::Array { inner, size } => {
                if let Some(s) = size {
                    let size_str = self.gen_expr_to_string(s);
                    format!("[{}]{}", size_str, self.type_str(inner))
                } else {
                    format!("[]{}", self.type_str(inner))
                }
            }
            Type::Tuple(types) => {
                let inner: Vec<String> = types.iter().map(|t| self.type_str(t)).collect();
                format!(".{{ {} }}", inner.join(", "))
            }
            Type::Generic { name, args } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.type_str(a)).collect();
                format!("{}({})", name, arg_strs.join(", "))
            }
            Type::Function { params, return_type } => {
                let param_strs: Vec<String> = params.iter().map(|p| self.type_str(p)).collect();
                format!("fn({}) {}", param_strs.join(", "), self.type_str(return_type))
            }
            Type::Unit => "void".to_string(),
            Type::Never => "noreturn".to_string(),
            Type::SelfType => "Self".to_string(),
            Type::RawPointer { inner, is_mut } => {
                if *is_mut {
                    format!("*{}", self.type_str(inner))
                } else {
                    format!("*const {}", self.type_str(inner))
                }
            }
        }
    }

    /// Generate an expression to a temporary string.
    fn gen_expr_to_string(&mut self, expr: &Expr) -> String {
        let saved_len = self.output.len();
        self.gen_expr(expr);
        let result = self.output[saved_len..].to_string();
        self.output.truncate(saved_len);
        result
    }
}

impl CodeGenerator for ZigCodeGen {
    fn generate(&mut self, program: &Program) -> String {
        self.generate_zig(program)
    }

    fn target_name(&self) -> &str {
        "zig"
    }

    fn file_extension(&self) -> &str {
        ".zig"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::Parser;

    fn transpile_to_zig(source: &str) -> String {
        let mut parser = Parser::new(source).unwrap();
        let program = parser.parse_program().unwrap();
        let mut gen = ZigCodeGen::new();
        gen.generate(&program)
    }

    #[test]
    fn test_zig_hello_world() {
        let src = r#"
            fn main() {
                println!("Hello, Zig!")
            }
        "#;
        let output = transpile_to_zig(src);
        assert!(output.contains("fn main()"));
        assert!(output.contains("std.debug.print"));
    }

    #[test]
    fn test_zig_struct() {
        let src = r#"
            struct Point {
                pub x: f64,
                pub y: f64,
            }
        "#;
        let output = transpile_to_zig(src);
        assert!(output.contains("const Point = struct"));
        assert!(output.contains("pub x: f64"));
    }

    #[test]
    fn test_zig_function_with_params() {
        let src = r#"
            fn add(a: i32, b: i32) -> i32 {
                return a + b
            }
        "#;
        let output = transpile_to_zig(src);
        assert!(output.contains("fn add("));
        assert!(output.contains("-> i32"));
    }

    #[test]
    fn test_zig_if_else() {
        let src = r#"
            fn check(x: i32) {
                if x > 0 {
                    println!("positive")
                } else {
                    println!("non-positive")
                }
            }
        "#;
        let output = transpile_to_zig(src);
        assert!(output.contains("if ("));
        assert!(output.contains("} else {"));
    }

    #[test]
    fn test_zig_while_loop() {
        let src = r#"
            fn countdown(n: i32) {
                let mut i = n
                while i > 0 {
                    println!("{}", i)
                    i = i - 1
                }
            }
        "#;
        let output = transpile_to_zig(src);
        assert!(output.contains("while ("));
    }
}
