use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

/// Python code generator — transpiles Ruva AST to Python source code.
///
/// Python is excellent for security-focused applications:
/// - No memory corruption (GC-managed)
/// - No buffer overflows
/// - Rich security libraries (cryptography, hashlib, ssl)
/// - Easy to audit and review
/// - Dynamic typing catches many class of errors at runtime
pub struct PythonCodeGen {
    output: String,
    indent: usize,
}

impl PythonCodeGen {
    pub fn new() -> Self {
        Self {
            output: String::with_capacity(4096),
            indent: 0,
        }
    }

    fn write_indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        writeln!(self.output, "{}", s).unwrap();
    }

    fn write(&mut self, s: &str) {
        self.output.push_str(s);
    }

    // ─── Top-level generation ───────────────────────────────────────────

    pub fn generate_python(&mut self, program: &Program) -> String {
        self.writeln("# Generated by the Ruva transpiler (Python backend) — do not edit");
        self.writeln("# Python target: security-focused, GC-managed, easy to audit");
        self.writeln("");
        self.writeln("from __future__ import annotations");
        self.writeln("from typing import Optional, Union, Any");
        self.writeln("from enum import Enum, auto");
        self.writeln("from dataclasses import dataclass");
        self.writeln("import sys");
        self.writeln("");

        for item in &program.items {
            self.gen_item(item);
        }

        std::mem::take(&mut self.output)
    }

    // ─── Items ──────────────────────────────────────────────────────────

    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Class(c) => self.gen_class(c),
            Item::Enum(e) => self.gen_enum(e),
            Item::Impl(imp) => self.gen_impl(imp),
            Item::Trait(t) => self.gen_trait(t),
            Item::TypeAlias(ta) => self.gen_type_alias(ta),
            Item::Const(c) => {
                self.output.push_str(&c.name);
                self.output.push_str(" = ");
                self.gen_expr(&c.value);
                self.writeln("");
            }
            Item::Import(imp) => self.gen_import(imp),
            Item::Use(u) => self.gen_use(u),
            Item::Attribute(attr) => self.gen_attribute(attr),
            Item::Module(m) => self.gen_module(m),
            Item::ExternBlock(eb) => self.gen_extern_block(eb),
            _ => self.writeln("# Unsupported item"),
        }
    }

    // ─── Functions ──────────────────────────────────────────────────────

    fn gen_function(&mut self, f: &FunctionDef) {
        if f.is_test {
            self.writeln("# @test");
        }

        // Python doesn't have pub/private at the language level,
        // but we use naming convention (_ prefix for private)
        let name = if f.is_pub || f.name == "main" {
            f.name.clone()
        } else {
            format!("_{}", f.name)
        };

        // Parameters
        let params: Vec<String> = f.params.iter().map(|p| {
            if let Type::SelfType = &p.ty {
                "self".to_string()
            } else {
                let ty_hint = match &p.ty {
                    Type::Name(name) => {
                        let py_type = self.python_type_hint(name);
                        if p.is_ref || p.is_mut {
                            format!(": {}", py_type)
                        } else {
                            format!(": {}", py_type)
                        }
                    }
                    _ => format!(": {}", self.type_str(&p.ty)),
                };
                format!("{}{}", p.name, ty_hint)
            }
        }).collect();

        // Return type
        let ret = match &f.return_type {
            Some(ty) => format!(" -> {}", self.type_str(ty)),
            None => String::new(),
        };

        self.writeln(&format!("def {}({}){}:", name, params.join(", "), ret));
        self.indent += 1;

        if f.body.stmts.is_empty() && f.body.expr.is_none() {
            self.writeln("pass");
        } else {
            self.gen_block(&f.body);
        }

        self.indent -= 1;
        self.writeln("");
        self.writeln("");
    }

    // ─── Structs (dataclass) ────────────────────────────────────────────

    fn gen_struct(&mut self, s: &StructDef) {
        self.writeln("@dataclass");
        self.writeln(&format!("class {}:", s.name));
        self.indent += 1;

        if s.fields.is_empty() {
            self.writeln("pass");
        } else {
            for field in &s.fields {
                let ty = self.type_str(&field.ty);
                self.writeln(&format!("{}: {}", field.name, ty));
            }

            // Generate __init__ if needed (dataclass auto-generates it)
            // But we add a __post_init__ for validation if there are constraints
            self.writeln("");
            self.writeln("def __post_init__(self):");
            self.indent += 1;
            self.writeln("pass  # Add validation here");
            self.indent -= 1;
        }

        self.indent -= 1;
        self.writeln("");
        self.writeln("");
    }

    // ─── Enums ──────────────────────────────────────────────────────────

    fn gen_enum(&mut self, e: &EnumDef) {
        // Check if any variant has fields
        let has_data = e.variants.iter().any(|v| !v.fields.is_empty());

        if has_data {
            // Use class-based enum for variants with data
            self.writeln(&format!("class {}(Enum):", e.name));
            self.indent += 1;

            for (i, variant) in e.variants.iter().enumerate() {
                if variant.fields.is_empty() {
                    if i == 0 {
                        self.writeln(&format!("{} = auto()", variant.name));
                    } else {
                        self.writeln(&format!("{} = auto()", variant.name));
                    }
                } else {
                    // For variants with data, use a class
                    self.writeln(&format!("class {}_data:", variant.name));
                    self.indent += 1;
                    for (j, ty) in variant.fields.iter().enumerate() {
                        let ty_str = self.type_str(ty);
                        self.writeln(&format!("field_{}: {}", j, ty_str));
                    }
                    self.indent -= 1;
                    self.writeln(&format!("{} = auto()", variant.name));
                }
            }

            self.indent -= 1;
        } else {
            // Simple enum
            self.writeln(&format!("class {}(Enum):", e.name));
            self.indent += 1;

            for variant in &e.variants {
                self.writeln(&format!("{} = auto()", variant.name));
            }

            self.indent -= 1;
        }

        self.writeln("");
        self.writeln("");
    }

    // ─── Classes ────────────────────────────────────────────────────────

    fn gen_class(&mut self, c: &ClassDef) {
        self.writeln(&format!("class {}:", c.name));
        self.indent += 1;

        if c.fields.is_empty() && c.methods.is_empty() {
            self.writeln("pass");
        } else {
            // Fields as __init__ parameters
            if !c.fields.is_empty() {
                self.writeln("def __init__(self, ");
                self.indent += 1;
                for (i, field) in c.fields.iter().enumerate() {
                    let ty = self.type_str(&field.ty);
                    if i > 0 {
                        self.write(",\n");
                        self.write_indent();
                    }
                    self.write(&format!("{}: {}", field.name, ty));
                }
                self.writeln("):");
                self.indent += 1;
                for field in &c.fields {
                    self.writeln(&format!("self.{} = {}", field.name, field.name));
                }
                self.indent -= 1;
                self.writeln("");
                self.indent -= 1;
            }

            // Methods
            for method in &c.methods {
                self.gen_method_in_class(method);
            }
        }

        self.indent -= 1;
        self.writeln("");
        self.writeln("");
    }

    fn gen_method_in_class(&mut self, f: &FunctionDef) {
        let name = &f.name;

        let params: Vec<String> = f.params.iter().map(|p| {
            if let Type::SelfType = &p.ty {
                "self".to_string()
            } else {
                let ty = self.type_str(&p.ty);
                format!("{}: {}", p.name, ty)
            }
        }).collect();

        let ret = match &f.return_type {
            Some(ty) => format!(" -> {}", self.type_str(ty)),
            None => String::new(),
        };

        self.writeln(&format!("def {}({}){}:", name, params.join(", "), ret));
        self.indent += 1;

        if f.body.stmts.is_empty() && f.body.expr.is_none() {
            self.writeln("pass");
        } else {
            self.gen_block(&f.body);
        }

        self.indent -= 1;
        self.writeln("");
    }

    // ─── Impl Blocks ────────────────────────────────────────────────────

    fn gen_impl(&mut self, imp: &ImplBlock) {
        // In Python, impl blocks become methods added to the class
        let self_type = self.type_str(&imp.self_type);
        self.writeln(&format!("# impl {} (methods added to class)", self_type));

        for method in &imp.methods {
            self.gen_function(method);
        }
    }

    // ─── Traits (Protocol) ─────────────────────────────────────────────

    fn gen_trait(&mut self, t: &TraitDef) {
        // Python uses Protocol for structural typing
        self.writeln("from typing import Protocol");
        self.writeln("");
        self.writeln(&format!("class {}(Protocol):", t.name));
        self.indent += 1;

        if t.methods.is_empty() {
            self.writeln("pass");
        } else {
            for method in &t.methods {
                let params: Vec<String> = method.params.iter().map(|p| {
                    if let Type::SelfType = &p.ty {
                        "self".to_string()
                    } else {
                        let ty = self.type_str(&p.ty);
                        format!("{}: {}", p.name, ty)
                    }
                }).collect();

                let ret = match &method.return_type {
                    Some(ty) => format!(" -> {}", self.type_str(ty)),
                    None => String::new(),
                };

                if let Some(ref body) = method.default_body {
                    self.writeln(&format!("def {}({}){}:", method.name, params.join(", "), ret));
                    self.indent += 1;
                    self.gen_block(body);
                    self.indent -= 1;
                } else {
                    self.writeln(&format!("def {}({}){}: ...", method.name, params.join(", "), ret));
                }
            }
        }

        self.indent -= 1;
        self.writeln("");
        self.writeln("");
    }

    // ─── Type Alias ─────────────────────────────────────────────────────

    fn gen_type_alias(&mut self, ta: &TypeAliasDef) {
        let ty = self.type_str(&ta.ty);
        self.writeln(&format!("{} = {}", ta.name, ty));
        self.writeln("");
    }

    // ─── Imports ────────────────────────────────────────────────────────

    fn gen_import(&mut self, imp: &ImportDef) {
        if imp.path.starts_with("ruva::") {
            let parts: Vec<&str> = imp.path.split("::").collect();
            if let Some(name) = parts.last() {
                // Map common ruva modules to Python equivalents
                match *name {
                    "crypto" => self.writeln("from cryptography.fernet import Fernet"),
                    "hash" => self.writeln("import hashlib"),
                    "random" => self.writeln("import secrets  # cryptographically secure"),
                    _ => self.writeln(&format!("import {}", name)),
                }
            }
        } else {
            if let Some(ref alias) = imp.alias {
                self.writeln(&format!("import {} as {}", imp.path, alias));
            } else {
                self.writeln(&format!("import {}", imp.path));
            }
        }
    }

    // ─── Attributes ─────────────────────────────────────────────────────

    fn gen_attribute(&mut self, attr: &Attribute) {
        self.writeln(&format!("# @{}", attr.name));
        self.gen_item(&attr.item);
    }

    // ─── Module ─────────────────────────────────────────────────────────

    fn gen_use(&mut self, u: &UseDef) {
        let path_str = u.path.join(".");
        if u.wildcard {
            self.writeln(&format!("from {} import *", path_str));
        } else if !u.selective.is_empty() {
            let items: Vec<String> = u.selective.iter().map(|item| {
                if let Some(ref alias) = item.alias {
                    format!("{} as {}", item.name, alias)
                } else {
                    item.name.clone()
                }
            }).collect();
            self.writeln(&format!("from {} import {}", path_str, items.join(", ")));
        } else if let Some(ref alias) = u.alias {
            self.writeln(&format!("import {} as {}", path_str, alias));
        } else if let Some(last) = u.path.last() {
            if u.path.len() > 1 {
                let mod_path = u.path[..u.path.len()-1].join(".");
                self.writeln(&format!("from {} import {}", mod_path, last));
            } else {
                self.writeln(&format!("import {}", path_str));
            }
        }
    }

    fn gen_module(&mut self, m: &ModDef) {
        if let Some(ref body) = m.body {
            self.writeln(&format!("class {}:", m.name));
            self.indent += 1;
            if body.is_empty() {
                self.writeln("pass");
            } else {
                for item in body {
                    self.gen_item(item);
                }
            }
            self.indent -= 1;
        } else {
            self.writeln(&format!("# module {} (file-based)", m.name));
            self.writeln(&format!("import {}", m.name));
        }
    }

    fn gen_extern_block(&mut self, eb: &ExternBlock) {
        self.writeln("import ctypes");
        self.writeln(&format!("# extern \"{}\" {{", eb.abi));
        let items: Vec<ExternItem> = eb.items.iter().cloned().collect();
        for item in &items {
            match item {
                ExternItem::Function { is_pub: _, ref name, params: _, return_type: _ } => {
                    self.writeln(&format!("# extern fn {}(...)", name));
                    self.writeln(&format!("{} = ctypes.CFUNCTYPE(None)(None)  # placeholder", name));
                }
                ExternItem::Static { is_pub: _, is_mut: _, ref name, ref ty } => {
                    let ty_str = self.type_str(ty);
                    self.writeln(&format!("# extern static {}: {}", name, ty_str));
                }
                ExternItem::Const { is_pub: _, ref name, ref ty, value: _ } => {
                    let ty_str = self.type_str(ty);
                    self.writeln(&format!("# extern const {}: {}", name, ty_str));
                }
            }
        }
        self.writeln("# }");
    }

    // ─── Blocks ─────────────────────────────────────────────────────────

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }

        if let Some(ref expr) = block.expr {
            self.write_indent();
            self.gen_expr(expr);
            self.output.push('\n');
        }
    }

    // ─── Statements ─────────────────────────────────────────────────────

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, ty, is_mut: _, value } => {
                let pat_str = self.pattern_str(pattern);
                if let Some(t) = ty {
                    let ty_str = self.type_str(t);
                    let val_str = self.gen_expr_to_string(value);
                    self.write_indent();
                    self.writeln(&format!("{}: {} = {}", pat_str, ty_str, val_str));
                } else {
                    let val_str = self.gen_expr_to_string(value);
                    self.write_indent();
                    self.writeln(&format!("{} = {}", pat_str, val_str));
                }
            }
            Stmt::Expr(expr) => {
                self.write_indent();
                self.gen_expr(expr);
                self.output.push('\n');
            }
            Stmt::Return(expr) => {
                self.write_indent();
                if let Some(e) = expr {
                    write!(self.output, "return ").unwrap();
                    self.gen_expr(e);
                    self.output.push('\n');
                } else {
                    self.output.push_str("return\n");
                }
            }
            Stmt::If { condition, then_body, else_body } => {
                self.write_indent();
                self.output.push_str("if ");
                self.gen_expr(condition);
                self.output.push_str(":\n");
                self.indent += 1;
                if then_body.stmts.is_empty() && then_body.expr.is_none() {
                    self.writeln("pass");
                } else {
                    self.gen_block(then_body);
                }
                self.indent -= 1;

                if let Some(else_kind) = else_body {
                    match else_kind {
                        ElseKind::If(cond, body) => {
                            self.write_indent();
                            self.output.push_str("elif ");
                            self.gen_expr(cond);
                            self.output.push_str(":\n");
                            self.indent += 1;
                            self.gen_block(body);
                            self.indent -= 1;
                        }
                        ElseKind::Else(body) => {
                            self.write_indent();
                            self.output.push_str("else:\n");
                            self.indent += 1;
                            self.gen_block(body);
                            self.indent -= 1;
                        }
                    }
                }
            }
            Stmt::For { pattern, iterable, body } => {
                let pat_str = self.pattern_str(pattern);
                self.write_indent();
                write!(self.output, "for {} in ", pat_str).unwrap();
                self.gen_expr(iterable);
                self.output.push_str(":\n");
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
            }
            Stmt::While { condition, body } => {
                self.write_indent();
                self.output.push_str("while ");
                self.gen_expr(condition);
                self.output.push_str(":\n");
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
            }
            Stmt::WhileLet { pattern, value, body } => {
                // Python: while with walrus operator or while True + if
                let pat_str = self.pattern_str(pattern);
                self.write_indent();
                self.output.push_str("while True:\n");
                self.indent += 1;
                let val_str = self.gen_expr_to_string(value);
                self.write_indent();
                self.writeln(&format!("match {}:", val_str));
                self.indent += 1;
                self.write_indent();
                self.writeln(&format!("case {}:", pat_str));
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.write_indent();
                self.writeln("case _:");
                self.indent += 1;
                self.writeln("break");
                self.indent -= 1;
                self.indent -= 1;
                self.indent -= 1;
            }
            Stmt::Loop(body) => {
                self.write_indent();
                self.output.push_str("while True:\n");
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
            }
            Stmt::Break(expr) => {
                self.write_indent();
                if let Some(e) = expr {
                    write!(self.output, "break  # ").unwrap();
                    self.gen_expr(e);
                    self.output.push('\n');
                } else {
                    self.output.push_str("break\n");
                }
            }
            Stmt::Continue => {
                self.writeln("continue");
            }
            Stmt::Match { expr, arms } => {
                // Python 3.10+ match/case
                self.write_indent();
                self.output.push_str("match ");
                self.gen_expr(expr);
                self.output.push_str(":\n");
                self.indent += 1;

                for arm in arms {
                    self.write_indent();
                    let pat = self.pattern_str(&arm.pattern);
                    self.writeln(&format!("case {}:", pat));
                    self.indent += 1;
                    self.gen_expr(&arm.body);
                    self.output.push('\n');
                    self.indent -= 1;
                }

                self.indent -= 1;
            }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {
                self.writeln("try:");
                self.indent += 1;
                self.gen_block(try_body);
                self.indent -= 1;
                self.write_indent();
                self.writeln(&format!("except Exception as {}:", catch_param));
                self.indent += 1;
                self.gen_block(catch_body);
                self.indent -= 1;
            }
            Stmt::Block(block) => {
                self.gen_block(block);
            }
            Stmt::Unsafe(block) => {
                // Python doesn't have unsafe — just generate the block with a comment
                self.writeln("# unsafe");
                self.gen_block(block);
            }
        }
    }

    // ─── Expressions ────────────────────────────────────────────────────

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "{}", n).unwrap(),
            Expr::Float(f) => {
                let s = format!("{}", f);
                if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                    write!(self.output, "{}.0", s).unwrap();
                } else {
                    write!(self.output, "{}", s).unwrap();
                }
            }
            Expr::Str(s) => write!(self.output, "\"{}\"", s).unwrap(),
            Expr::Char(c) => write!(self.output, "\"{}\"", c).unwrap(),
            Expr::Bool(b) => {
                if *b {
                    self.output.push_str("True");
                } else {
                    self.output.push_str("False");
                }
            }
            Expr::Null => self.output.push_str("None"),
            Expr::Self_ => self.output.push_str("self"),
            Expr::Ident(name) => self.output.push_str(name),

            Expr::Path(path) => {
                let s = path.join(".");
                self.output.push_str(&s);
            }

            Expr::Array(elements) => {
                self.output.push('[');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                self.output.push(']');
            }

            Expr::ArrayRepeat { value, size } => {
                // Python repeat: [value] * size
                self.output.push('[');
                self.gen_expr(value);
                self.output.push_str("] * ");
                self.gen_expr(size);
            }

            Expr::Tuple(elements) => {
                self.output.push('(');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                if elements.len() == 1 {
                    self.output.push(',');
                }
                self.output.push(')');
            }

            Expr::Range { start, end, inclusive } => {
                self.output.push_str("range(");
                self.gen_expr(start);
                self.output.push_str(", ");
                if *inclusive {
                    // range is exclusive in Python, so add 1
                    self.gen_expr(end);
                    self.output.push_str(" + 1");
                } else {
                    self.gen_expr(end);
                }
                self.output.push(')');
            }

            Expr::Binary { op, left, right } => {
                self.output.push('(');
                self.gen_expr(left);
                // Map Rust operators to Python
                let op_str = match op {
                    BinOp::And => "and",
                    BinOp::Or => "or",
                    BinOp::Rem => "%",
                    BinOp::BitAnd => "&",
                    BinOp::BitOr => "|",
                    BinOp::BitXor => "^",
                    BinOp::Shl => "<<",
                    BinOp::Shr => ">>",
                    _ => &format!("{}", op),
                };
                write!(self.output, " {} ", op_str).unwrap();
                self.gen_expr(right);
                self.output.push(')');
            }

            Expr::Unary { op, expr } => {
                match op {
                    UnaryOp::Neg => self.output.push('-'),
                    UnaryOp::Not => {
                        self.output.push_str("not ");
                    }
                    UnaryOp::Deref => {
                        // Python has no dereferencing
                    }
                }
                self.gen_expr(expr);
            }

            Expr::Assign { target, value } => {
                self.gen_expr(target);
                self.output.push_str(" = ");
                self.gen_expr(value);
            }

            Expr::CompoundAssign { op, target, value } => {
                self.gen_expr(target);
                write!(self.output, " {}= ", op).unwrap();
                self.gen_expr(value);
            }

            Expr::Call { function, args } => {
                self.gen_expr(function);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::MethodCall { object, method, args } => {
                // Python: object.method(args)
                self.gen_expr(object);
                self.output.push('.');
                self.output.push_str(method);
                self.output.push('(');
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(arg);
                }
                self.output.push(')');
            }

            Expr::Field { object, field } => {
                self.gen_expr(object);
                self.output.push('.');
                self.output.push_str(field);
            }

            Expr::Index { object, index } => {
                self.gen_expr(object);
                self.output.push('[');
                self.gen_expr(index);
                self.output.push(']');
            }

            Expr::Closure { params, return_type: _, body } => {
                // Python: lambda for simple closures, def for complex ones
                self.output.push_str("lambda ");
                for (i, p) in params.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.output.push_str(&p.name);
                }
                self.output.push_str(": ");
                self.gen_expr(body);
            }

            Expr::Block(block) => {
                // Python doesn't have block expressions, use a function
                self.output.push_str("(lambda: (\n");
                self.indent += 1;
                self.gen_block(block);
                self.indent -= 1;
                self.write_indent();
                self.output.push_str("))()");
            }

            Expr::UnsafeBlock(body) => {
                // Python doesn't have unsafe — just generate the block
                self.gen_block(body);
            }
            Expr::Sizeof(_ty) => {
                // Python doesn't have sizeof — use sys.getsizeof
                write!(self.output, "sys.getsizeof(None)").unwrap();
            }
            Expr::Offsetof { .. } => {
                // Python doesn't have offsetof — use a placeholder
                write!(self.output, "0").unwrap();
            }
            Expr::NullPtr => {
                write!(self.output, "None").unwrap();
            }
            Expr::Loop(body) => {
                self.output.push_str("(lambda: (\n");
                self.indent += 1;
                self.writeln("while True:");
                self.indent += 1;
                self.gen_block(body);
                self.indent -= 1;
                self.indent -= 1;
                self.write_indent();
                self.output.push_str("))()");
            }

            Expr::If { condition, then_body, else_body } => {
                // Python ternary: value_if_true if condition else value_if_false
                // For block expressions, we need to use a different approach
                self.gen_block(then_body);
                self.output.push_str(" if ");
                self.gen_expr(condition);
                self.output.push_str(" else ");
                if let Some(ref else_expr) = else_body {
                    self.gen_expr(else_expr);
                } else {
                    self.output.push_str("None");
                }
            }

            Expr::Match { expr, arms } => {
                // Python 3.10+ match/case
                self.output.push_str("match ");
                self.gen_expr(expr);
                self.output.push_str(":\n");
                self.indent += 1;
                for arm in arms {
                    self.write_indent();
                    let pat = self.pattern_str(&arm.pattern);
                    self.writeln(&format!("case {}:", pat));
                    self.indent += 1;
                    self.gen_expr(&arm.body);
                    self.output.push('\n');
                    self.indent -= 1;
                }
                self.indent -= 1;
            }

            Expr::Try(expr) => {
                // Python: try/except
                self.gen_expr(expr);
            }

            Expr::Cast { expr, ty } => {
                // Python: type conversion
                let ty_str = self.type_str(ty);
                match ty_str.as_str() {
                    "int" | "i32" | "i64" | "u32" | "u64" => {
                        write!(self.output, "int(").unwrap();
                        self.gen_expr(expr);
                        self.output.push(')');
                    }
                    "f32" | "f64" | "float" => {
                        write!(self.output, "float(").unwrap();
                        self.gen_expr(expr);
                        self.output.push(')');
                    }
                    "str" | "string" => {
                        write!(self.output, "str(").unwrap();
                        self.gen_expr(expr);
                        self.output.push(')');
                    }
                    "bool" => {
                        write!(self.output, "bool(").unwrap();
                        self.gen_expr(expr);
                        self.output.push(')');
                    }
                    _ => {
                        self.gen_expr(expr);
                    }
                }
            }

            Expr::Macro { name, args } => {
                match name.as_str() {
                    "println" => {
                        self.output.push_str("print(");
                        // Format string handling
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.output.push(')');
                    }
                    "print" => {
                        self.output.push_str("print(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.output.push(')');
                    }
                    "format" => {
                        self.output.push_str("f\"");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(" ");
                            }
                            self.gen_expr(arg);
                        }
                        self.output.push('"');
                    }
                    "vec" => {
                        self.output.push('[');
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.output.push(']');
                    }
                    _ => {
                        self.output.push_str(name);
                        self.output.push('(');
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.output.push_str(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.output.push(')');
                    }
                }
            }

            Expr::Reference { expr, is_mut: _ } => {
                // Python has no references
                self.gen_expr(expr);
            }

            Expr::Deref(expr) => {
                // Python has no dereferencing
                self.gen_expr(expr);
            }

            Expr::Move(expr) => {
                // Python has no move semantics
                self.gen_expr(expr);
            }

            Expr::VecLit(elements) => {
                self.output.push('[');
                for (i, el) in elements.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.gen_expr(el);
                }
                self.output.push(']');
            }

            Expr::StructLiteral { name, fields } => {
                if matches!(name.as_ref(), Expr::Self_) {
                    self.output.push_str("Self");
                } else {
                    self.gen_expr(name);
                }
                self.output.push('(');
                for (i, (field_name, value)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    write!(self.output, "{}=", field_name).unwrap();
                    self.gen_expr(value);
                }
                self.output.push(')');
            }

            // New features — Python fallbacks
            Expr::FString(parts) => {
                self.output.push_str("f\"");
                for part in parts {
                    match part {
                        crate::ast::FStringPart::Text(text) => self.output.push_str(text),
                        crate::ast::FStringPart::Expr(expr) => {
                            self.output.push_str("{");
                            self.gen_expr(expr);
                            self.output.push('}');
                        }
                    }
                }
                self.output.push('"');
            }
            Expr::OptionalChaining { object, field } => {
                self.gen_expr(object);
                write!(self.output, ".{}", field).unwrap();
            }
            Expr::NullCoalesce { left, right } => {
                self.gen_expr(left);
                self.output.push_str(" or ");
                self.gen_expr(right);
            }
            Expr::Assert { condition, message } => {
                self.output.push_str("assert ");
                self.gen_expr(condition);
                if let Some(ref msg) = message {
                    self.output.push_str(", ");
                    self.gen_expr(msg);
                }
            }
            Expr::AssertEq { left, right, message } => {
                self.output.push_str("assert ");
                self.gen_expr(left);
                self.output.push_str(" == ");
                self.gen_expr(right);
                if let Some(ref msg) = message {
                    self.output.push_str(", ");
                    self.gen_expr(msg);
                }
            }
            Expr::AssertNe { left, right, message } => {
                self.output.push_str("assert ");
                self.gen_expr(left);
                self.output.push_str(" != ");
                self.gen_expr(right);
                if let Some(ref msg) = message {
                    self.output.push_str(", ");
                    self.gen_expr(msg);
                }
            }
            _ => self.output.push_str("None"),
        }
    }

    // ─── Patterns ───────────────────────────────────────────────────────

    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat {
            Pattern::Wildcard => "_".to_string(),
            Pattern::Ident(name) => name.clone(),
            Pattern::Literal(expr) => self.gen_expr_to_string(expr),
            Pattern::Tuple(patterns) => {
                let inner: Vec<String> = patterns.iter().map(|p| self.pattern_str(p)).collect();
                format!("({})", inner.join(", "))
            }
            Pattern::Enum { path, fields } => {
                // path already contains the variant name as its last element,
                // so just join with "." — no need to append variant separately.
                let path_str = path.join(".");
                if fields.is_empty() {
                    path_str
                } else {
                    let field_strs: Vec<String> = fields.iter().map(|f| self.pattern_str(f)).collect();
                    format!("{}({})", path_str, field_strs.join(", "))
                }
            }
            Pattern::Struct { path, fields } => {
                let name = path.join(".");
                let field_strs: Vec<String> = fields.iter().map(|(n, p)| {
                    let p_str = self.pattern_str(p);
                    if n == &p_str {
                        n.clone()
                    } else {
                        format!("{}={}", n, p_str)
                    }
                }).collect();
                format!("{}({})", name, field_strs.join(", "))
            }
            Pattern::Range { start, end, inclusive } => {
                let s = self.gen_expr_to_string(start);
                let e = self.gen_expr_to_string(end);
                if *inclusive {
                    format!("range({}, {} + 1)", s, e)
                } else {
                    format!("range({}, {})", s, e)
                }
            }
            Pattern::Or(patterns) => {
                let inner: Vec<String> = patterns.iter().map(|p| self.pattern_str(p)).collect();
                inner.join(" | ")
            }
            Pattern::Reference(inner) => {
                self.pattern_str(inner)
            }
            Pattern::Mut(name) => {
                name.clone()
            }
        }
    }

    // ─── Types ──────────────────────────────────────────────────────────

    fn python_type_hint(&self, name: &str) -> String {
        match name {
            "i8" | "i16" | "i32" | "i64" | "i128" | "isize" => "int".to_string(),
            "u8" | "u16" | "u32" | "u64" | "u128" | "usize" => "int".to_string(),
            "f32" | "f64" => "float".to_string(),
            "bool" => "bool".to_string(),
            "char" | "string" => "str".to_string(),
            "()" => "None".to_string(),
            _ => name.to_string(),
        }
    }

    fn type_str(&mut self, ty: &Type) -> String {
        match ty {
            Type::Name(name) => self.python_type_hint(name),
            Type::Path(path) => path.join("."),
            Type::Reference { inner, is_mut: _ } => {
                // Python has no reference types
                self.type_str(inner)
            }
            Type::Slice(inner) => {
                format!("list[{}]", self.type_str(inner))
            }
            Type::Array { inner, size: _ } => {
                format!("list[{}]", self.type_str(inner))
            }
            Type::Tuple(types) => {
                let inner: Vec<String> = types.iter().map(|t| self.type_str(t)).collect();
                format!("tuple[{}]", inner.join(", "))
            }
            Type::Generic { name, args } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.type_str(a)).collect();
                format!("{}[{}]", name, arg_strs.join(", "))
            }
            Type::Function { params, return_type } => {
                let param_strs: Vec<String> = params.iter().map(|p| self.type_str(p)).collect();
                format!("Callable[[{}], {}]", param_strs.join(", "), self.type_str(return_type))
            }
            Type::Unit => "None".to_string(),
            Type::Never => "NoReturn".to_string(),
            Type::SelfType => "Self".to_string(),
            Type::RawPointer { inner, is_mut: _ } => {
                // Python uses ctypes for raw pointers
                format!("ctypes.POINTER({})", self.type_str(inner))
            }
        }
    }

    /// Generate an expression to a temporary string.
    fn gen_expr_to_string(&mut self, expr: &Expr) -> String {
        let saved_len = self.output.len();
        self.gen_expr(expr);
        let result = self.output[saved_len..].to_string();
        self.output.truncate(saved_len);
        result
    }
}

impl CodeGenerator for PythonCodeGen {
    fn generate(&mut self, program: &Program) -> String {
        self.generate_python(program)
    }

    fn target_name(&self) -> &str {
        "python"
    }

    fn file_extension(&self) -> &str {
        ".py"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::Parser;

    fn transpile_to_python(source: &str) -> String {
        let mut parser = Parser::new(source).unwrap();
        let program = parser.parse_program().unwrap();
        let mut gen = PythonCodeGen::new();
        gen.generate(&program)
    }

    #[test]
    fn test_python_hello_world() {
        let src = r#"
            fn main() {
                println!("Hello, Python!")
            }
        "#;
        let output = transpile_to_python(src);
        assert!(output.contains("def main():"));
        assert!(output.contains("print("));
    }

    #[test]
    fn test_python_class() {
        let src = r#"
            class Dog {
                pub let name: string
                pub let mut energy: u32
            }
        "#;
        let output = transpile_to_python(src);
        assert!(output.contains("class Dog:"));
    }

    #[test]
    fn test_python_function_with_types() {
        let src = r#"
            pub fn add(a: i32, b: i32) -> i32 {
                return a + b
            }
        "#;
        let output = transpile_to_python(src);
        assert!(output.contains("def add("));
        assert!(output.contains("-> int:"));
    }

    #[test]
    fn test_python_if_else() {
        let src = r#"
            fn check(x: i32) {
                if x > 0 {
                    println!("positive")
                } else {
                    println!("non-positive")
                }
            }
        "#;
        let output = transpile_to_python(src);
        assert!(output.contains("if "));
        assert!(output.contains("else:"));
    }

    #[test]
    fn test_python_while_loop() {
        let src = r#"
            fn countdown(n: i32) {
                let mut i = n
                while i > 0 {
                    println!("{}", i)
                    i = i - 1
                }
            }
        "#;
        let output = transpile_to_python(src);
        assert!(output.contains("while "));
    }

    #[test]
    fn test_python_target_name() {
        let gen = PythonCodeGen::new();
        assert_eq!(gen.target_name(), "python");
        assert_eq!(gen.file_extension(), ".py");
    }

    #[test]
    fn test_python_enum_no_double_variant() {
        let src = r#"
            enum Status {
                Active,
                Inactive
            }

            fn check(s: Status) {
                match s {
                    Status::Active => println!("active")
                    Status::Inactive => println!("inactive")
                }
            }
        "#;
        let output = transpile_to_python(src);
        // Must NOT produce doubled variants like "Status.Active.Active"
        assert!(!output.contains("Status.Active.Active"),
            "doubled variant found in output");
        assert!(!output.contains("Status.Inactive.Inactive"),
            "doubled variant found in output");
        // Should produce correct Python enum patterns
        assert!(output.contains("Status.Active"));
        assert!(output.contains("Status.Inactive"));
    }
}
