use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

/// C# code generator — transpiles Ruva AST to C# source code.
pub struct CSharpCodeGen { output: String, indent: usize }

impl CSharpCodeGen {
    pub fn new() -> Self { Self { output: String::with_capacity(4096), indent: 0 } }
    fn write_indent(&mut self) { for _ in 0..self.indent { self.output.push_str("    "); } }
    fn writeln(&mut self, s: &str) { self.write_indent(); writeln!(self.output, "{}", s).unwrap(); }
    fn write(&mut self, s: &str) { self.output.push_str(s); }

    pub fn generate_csharp(&mut self, program: &Program) -> String {
        self.writeln("// Generated by the Ruva transpiler (C# backend) — do not edit");
        self.writeln("using System;");
        self.writeln("using System.Collections.Generic;");
        self.writeln("");
        for item in &program.items { self.gen_item(item); }
        std::mem::take(&mut self.output)
    }

    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Class(c) => self.gen_class(c),
            Item::Enum(e) => self.gen_enum(e),
            Item::Trait(t) => self.gen_trait(t),
            Item::TypeAlias(ta) => self.gen_type_alias(ta),
            Item::Import(imp) => self.gen_import(imp),
            Item::Module(m) => self.writeln(&format!("// module {}", m.name)),
            _ => self.writeln("// Unsupported item"),
        }
    }

    fn gen_function(&mut self, f: &FunctionDef) {
        let vis = if f.is_pub { "public " } else { "private " };
        let ret = match &f.return_type { Some(ty) => self.type_str(ty), None => "void".to_string() };
        let params: Vec<String> = f.params.iter().map(|p| {
            if let Type::SelfType = &p.ty { "this".to_string() } else { format!("{} {}", self.type_str(&p.ty), p.name) }
        }).collect();
        self.writeln(&format!("{}static {} {}({}) {{", vis, ret, f.name, params.join(", ")));
        self.indent += 1; self.gen_block(&f.body); self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_struct(&mut self, s: &StructDef) {
        self.writeln(&format!("public struct {} {{", s.name));
        self.indent += 1;
        for f in &s.fields { let v = if f.is_pub { "public" } else { "private" }; let _ty_x = self.type_str(&f.ty); self.writeln(&format!("{} {} {};", v, _ty_x, f.name)); }
        self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_enum(&mut self, e: &EnumDef) {
        self.writeln(&format!("public enum {} {{", e.name));
        self.indent += 1;
        for (i, v) in e.variants.iter().enumerate() {
            let comma = if i < e.variants.len() - 1 { "," } else { "" };
            self.writeln(&format!("{}{}", v.name, comma));
        }
        self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_class(&mut self, c: &ClassDef) {
        self.writeln(&format!("public class {} {{", c.name));
        self.indent += 1;
        for f in &c.fields { let v = if f.is_pub { "public" } else { "private" }; let _ty_x = self.type_str(&f.ty); self.writeln(&format!("{} {} {};", v, _ty_x, f.name)); }
        for m in &c.methods { self.gen_function(m); }
        self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_trait(&mut self, t: &TraitDef) {
        self.writeln(&format!("public interface {} {{", t.name));
        self.indent += 1;
        for m in &t.methods {
            let ret = match &m.return_type { Some(ty) => self.type_str(ty), None => "void".to_string() };
            let params: Vec<String> = m.params.iter().map(|p| format!("{} {}", self.type_str(&p.ty), p.name)).collect();
            self.writeln(&format!("{} {}({});", ret, m.name, params.join(", ")));
        }
        self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_type_alias(&mut self, ta: &TypeAliasDef) { let ty = self.type_str(&ta.ty); self.writeln(&format!("using {} = {};", ta.name, ty)); }
    fn gen_import(&mut self, imp: &ImportDef) { self.writeln(&format!("using {};", imp.path.replace("::", "."))); }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts { self.gen_stmt(stmt); }
        if let Some(ref expr) = block.expr { self.write_indent(); self.gen_expr(expr); self.output.push('\n'); }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, ty, is_mut: _, value } => {
                let ty_str = ty.as_ref().map(|t| format!("{} ", self.type_str(t))).unwrap_or_else(|| "var ".to_string());
                self.write_indent(); let _p = self.pattern_str(pattern); write!(self.output, "{}{} = ", ty_str, _p).unwrap();
                self.gen_expr(value); self.output.push_str(";\n");
            }
            Stmt::Expr(e) => { self.write_indent(); self.gen_expr(e); self.output.push_str(";\n"); }
            Stmt::Return(e) => { self.write_indent(); if let Some(e) = e { write!(self.output, "return ").unwrap(); self.gen_expr(e); self.output.push_str(";\n"); } else { self.output.push_str("return;\n"); } }
            Stmt::If { condition, then_body, else_body } => {
                self.write("if ("); self.gen_expr(condition); self.output.push_str(") {\n"); self.indent += 1; self.gen_block(then_body); self.indent -= 1; self.writeln("}");
                if let Some(ek) = else_body { match ek { ElseKind::If(c, b) => { self.write("else if ("); self.gen_expr(c); self.output.push_str(") {\n"); self.indent += 1; self.gen_block(b); self.indent -= 1; self.writeln("}"); } ElseKind::Else(b) => { self.output.push_str("else {\n"); self.indent += 1; self.gen_block(b); self.indent -= 1; self.writeln("}"); } } }
            }
            Stmt::For { pattern, iterable, body } => {
                self.write_indent(); let _p = self.pattern_str(pattern); write!(self.output, "foreach (var {} in ", _p).unwrap();
                self.gen_expr(iterable); self.output.push_str(") {\n"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("}");
            }
            Stmt::While { condition, body } => { self.write_indent(); self.output.push_str("while ("); self.gen_expr(condition); self.output.push_str(") {\n"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("}"); }
            Stmt::Loop(body) => { self.write_indent(); self.output.push_str("while (true) {\n"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("}"); }
            Stmt::Break(_) => { self.writeln("break;"); }
            Stmt::Continue => { self.writeln("continue;"); }
            Stmt::Match { .. } => { self.writeln("// match → switch"); }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {
                self.writeln("try {"); self.indent += 1; self.gen_block(try_body); self.indent -= 1;
                self.write_indent(); self.writeln(&format!("}} catch (Exception {}) {{", catch_param));
                self.indent += 1; self.gen_block(catch_body); self.indent -= 1; self.writeln("}");
            }
            Stmt::Block(b) => self.gen_block(b),
            Stmt::WhileLet { pattern, value, body } => {
                self.gen_stmt(&Stmt::While { condition: value.clone(), body: body.clone() });
            }
            Stmt::Unsafe(b) => self.gen_block(b),
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "{}", n).unwrap(),
            Expr::Float(f) => { let s = format!("{}", f); if !s.contains('.') { write!(self.output, "{}f", s).unwrap(); } else { write!(self.output, "{}", s).unwrap(); } }
            Expr::Str(s) => write!(self.output, "\"{}\"", s).unwrap(),
            Expr::Bool(b) => { if *b { self.output.push_str("true"); } else { self.output.push_str("false"); } }
            Expr::Null => self.output.push_str("null"),
            Expr::Self_ => self.output.push_str("this"),
            Expr::Ident(n) => self.output.push_str(n),
            Expr::Binary { op, left, right } => { self.output.push('('); self.gen_expr(left); write!(self.output, " {} ", op).unwrap(); self.gen_expr(right); self.output.push(')'); }
            Expr::Unary { op, expr } => { match op { UnaryOp::Neg => self.output.push('-'), UnaryOp::Not => self.output.push('!'), _ => {} }; self.gen_expr(expr); }
            Expr::Assign { target, value } => { self.gen_expr(target); self.output.push_str(" = "); self.gen_expr(value); }
            Expr::Call { function, args } => { self.gen_expr(function); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::MethodCall { object, method, args } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(method); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::Field { object, field } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(field); }
            Expr::Index { object, index } => { self.gen_expr(object); self.output.push('['); self.gen_expr(index); self.output.push(']'); }
            Expr::Macro { name, args } => {
                match name.as_str() {
                    "println" => { self.output.push_str("Console.WriteLine("); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                    "print" => { self.output.push_str("Console.Write("); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                    _ => { self.output.push_str(name); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                }
            }
            Expr::FString(parts) => { self.output.push('"'); for p in parts { match p { FStringPart::Text(t) => self.output.push_str(t), FStringPart::Expr(e) => { self.output.push_str("\"); Console.Write("); self.gen_expr(e); self.output.push_str("); Console.Write(\""); } } } self.output.push('"'); }
            _ => self.output.push_str("null"),
        }
    }

    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat { Pattern::Wildcard => "_".to_string(), Pattern::Ident(n) => n.clone(), Pattern::Literal(e) => self.gen_expr_to_string(e), _ => "_".to_string() }
    }

    fn type_str(&mut self, ty: &Type) -> String {
        match ty {
            Type::Name(n) => match n.as_str() { "i8" | "i16" | "i32" | "u8" | "u16" | "u32" => "int".to_string(), "i64" | "u64" | "isize" | "usize" => "long".to_string(), "f32" => "float".to_string(), "f64" => "double".to_string(), "bool" => "bool".to_string(), "char" => "char".to_string(), "string" => "string".to_string(), "()" => "void".to_string(), _ => n.clone() },
            Type::Generic { name, args } => { let a: Vec<String> = args.iter().map(|t| self.type_str(t)).collect(); format!("{}<{}>", name, a.join(", ")) }
            Type::Slice(inner) | Type::Array { inner, .. } => format!("List<{}>", self.type_str(inner)),
            _ => "object".to_string(),
        }
    }

    fn gen_expr_to_string(&mut self, expr: &Expr) -> String { let s = self.output.len(); self.gen_expr(expr); let r = self.output[s..].to_string(); self.output.truncate(s); r }
}

impl CodeGenerator for CSharpCodeGen {
    fn generate(&mut self, program: &Program) -> String { self.generate_csharp(program) }
    fn target_name(&self) -> &str { "csharp" }
    fn file_extension(&self) -> &str { ".cs" }
}
