use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

pub struct GoCodeGen { output: String, indent: usize }

impl GoCodeGen {
    pub fn new() -> Self { Self { output: String::with_capacity(4096), indent: 0 } }
    fn write_indent(&mut self) { for _ in 0..self.indent { self.output.push('\t'); } }
    fn writeln(&mut self, s: &str) { self.write_indent(); writeln!(self.output, "{}", s).unwrap(); }
    fn write(&mut self, s: &str) { self.output.push_str(s); }

    pub fn generate_go(&mut self, program: &Program) -> String {
        self.writeln("// Generated by the Ruva transpiler (Go backend) — do not edit");
        self.writeln("package main");
        self.writeln("");
        self.writeln("import (");
        self.writeln("    \"fmt\"");
        self.writeln(")");
        self.writeln("");
        for item in &program.items { self.gen_item(item); }
        std::mem::take(&mut self.output)
    }

    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Enum(e) => self.gen_enum(e),
            Item::Trait(t) => self.gen_trait(t),
            Item::Import(imp) => self.gen_import(imp),
            Item::Module(m) => self.writeln(&format!("// module {}", m.name)),
            _ => self.writeln("// Unsupported item"),
        }
    }

    fn gen_function(&mut self, f: &FunctionDef) {
        let name = if f.name == "main" { "main".to_string() } else { f.name.clone() };
        let ret = match &f.return_type { Some(ty) => format!(" {}", self.type_str(ty)), None => String::new() };
        let params: Vec<String> = f.params.iter().map(|p| format!("{} {}", p.name, self.type_str(&p.ty))).collect();
        self.writeln(&format!("func {}({}){} {{", name, params.join(", "), ret));
        self.indent += 1; self.gen_block(&f.body); self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_struct(&mut self, s: &StructDef) {
        self.writeln(&format!("type {} struct {{", s.name));
        self.indent += 1;
        for f in &s.fields { let name = to_pascal(&f.name); let _ty_x = self.type_str(&f.ty); self.writeln(&format!("{} {} `json:\"{}\"`", name, _ty_x, f.name)); }
        self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_enum(&mut self, e: &EnumDef) {
        self.writeln(&format!("type {} int", e.name));
        self.writeln("const (");
        self.indent += 1;
        for (i, v) in e.variants.iter().enumerate() {
            if i == 0 { self.writeln(&format!("{}{} = iota", e.name, v.name)); }
            else { self.writeln(&format!("{}{}", e.name, v.name)); }
        }
        self.indent -= 1; self.writeln(")"); self.writeln("");
    }

    fn gen_trait(&mut self, t: &TraitDef) {
        self.writeln(&format!("// {} — interface", t.name));
        self.writeln(&format!("type {} interface {{", t.name));
        self.indent += 1;
        for m in &t.methods {
            let ret = match &m.return_type { Some(ty) => self.type_str(ty), None => String::new() };
            let params: Vec<String> = m.params.iter().map(|p| format!("{} {}", p.name, self.type_str(&p.ty))).collect();
            self.writeln(&format!("{}({}) {}", m.name, params.join(", "), ret));
        }
        self.indent -= 1; self.writeln("}"); self.writeln("");
    }

    fn gen_import(&mut self, imp: &ImportDef) { self.writeln(&format!("// import {}", imp.path.replace("::", "/"))); }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts { self.gen_stmt(stmt); }
        if let Some(ref expr) = block.expr { self.write_indent(); self.gen_expr(expr); self.output.push('\n'); }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, ty, is_mut: _, value } => {
                let pat = self.pattern_str(pattern);
                if let Some(t) = ty { self.write_indent(); let _t = self.type_str(t); write!(self.output, "{} := {}", pat, _t).unwrap(); self.output.push_str(" /* type hint */\n"); }
                self.write_indent(); write!(self.output, "{} = ", pat).unwrap(); self.gen_expr(value); self.output.push('\n');
            }
            Stmt::Expr(e) => { self.write_indent(); self.gen_expr(e); self.output.push('\n'); }
            Stmt::Return(e) => { self.write_indent(); if let Some(e) = e { write!(self.output, "return ").unwrap(); self.gen_expr(e); self.output.push('\n'); } else { self.output.push_str("return\n"); } }
            Stmt::If { condition, then_body, else_body } => {
                self.write("if "); self.gen_expr(condition); self.output.push_str(" {\n"); self.indent += 1; self.gen_block(then_body); self.indent -= 1;
                if let Some(ek) = else_body { match ek {                        ElseKind::If(c, b) => { self.write_indent(); self.write("} else if "); self.gen_expr(c); self.output.push_str(" {\n"); self.indent += 1; self.gen_block(b); self.indent -= 1; } ElseKind::Else(b) => { self.writeln("} else {"); self.indent += 1; self.gen_block(b); self.indent -= 1; } } }
                self.writeln("}");
            }
            Stmt::For { pattern, iterable, body } => {
                let pat = self.pattern_str(pattern);
                self.write_indent(); write!(self.output, "for _, {} := range ", pat).unwrap(); self.gen_expr(iterable); self.output.push_str(" {\n");
                self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("}");
            }
            Stmt::While { condition, body } => { self.write_indent(); self.output.push_str("for "); self.gen_expr(condition); self.output.push_str(" {\n"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("}"); }
            Stmt::Loop(body) => { self.writeln("for {"); self.indent += 1; self.gen_block(body); self.indent -= 1; self.writeln("}"); }
            Stmt::Break(_) => { self.writeln("break"); }
            Stmt::Continue => { self.writeln("continue"); }
            Stmt::Match { .. } => { self.writeln("// match not yet supported in Go backend"); }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {
                self.gen_block(try_body);
                self.writeln(&format!("if err != nil {{ // catch {}", catch_param));
                self.indent += 1; self.gen_block(catch_body); self.indent -= 1; self.writeln("}");
            }
            Stmt::Block(b) => self.gen_block(b),
            Stmt::WhileLet { pattern, value, body } => {
                self.gen_stmt(&Stmt::While { condition: value.clone(), body: body.clone() });
            }
            Stmt::Unsafe(b) => self.gen_block(b),
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "{}", n).unwrap(),
            Expr::Float(f) => { let s = format!("{}", f); if !s.contains('.') { write!(self.output, "{}.0", s).unwrap(); } else { write!(self.output, "{}", s).unwrap(); } }
            Expr::Str(s) => write!(self.output, "\"{}\"", s).unwrap(),
            Expr::Bool(b) => { if *b { self.output.push_str("true"); } else { self.output.push_str("false"); } }
            Expr::Null => self.output.push_str("nil"),
            Expr::Self_ => self.output.push_str("self"),
            Expr::Ident(n) => self.output.push_str(n),
            Expr::Binary { op, left, right } => { self.output.push('('); self.gen_expr(left); write!(self.output, " {} ", op).unwrap(); self.gen_expr(right); self.output.push(')'); }
            Expr::Unary { op, expr } => { match op { UnaryOp::Neg => self.output.push('-'), UnaryOp::Not => self.output.push_str("!"), _ => {} }; self.gen_expr(expr); }
            Expr::Assign { target, value } => { self.gen_expr(target); self.output.push_str(" = "); self.gen_expr(value); }
            Expr::Call { function, args } => { self.gen_expr(function); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::MethodCall { object, method, args } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(method); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::Field { object, field } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(&to_pascal(field)); }
            Expr::Index { object, index } => { self.gen_expr(object); self.output.push('['); self.gen_expr(index); self.output.push(']'); }
            Expr::Macro { name, args, separator: _ } => {
                match name.as_str() {
                    "println" => { self.output.push_str("fmt.Println("); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                    _ => { self.output.push_str(name); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                }
            }
            Expr::FString(parts) => { self.output.push_str("fmt.Sprintf(\""); for p in parts { match p { FStringPart::Text(t) => self.output.push_str(&t.replace('{', "%v")), FStringPart::Expr(e) => { self.output.push_str("\", "); self.gen_expr(e); self.output.push_str(", fmt.Sprintf(\""); } } } self.output.push_str("\")"); }
            _ => self.output.push_str("nil"),
        }
    }

    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat { Pattern::Wildcard => "_".to_string(), Pattern::Ident(n) => n.clone(), Pattern::Literal(e) => self.gen_expr_to_string(e), _ => "_".to_string() }
    }

    fn type_str(&mut self, ty: &Type) -> String {
        match ty {
            Type::Name(n) => match n.as_str() { "i8" | "i16" | "i32" | "u8" | "u16" | "u32" => "int32".to_string(), "i64" | "u64" | "isize" | "usize" => "int64".to_string(), "f32" => "float32".to_string(), "f64" => "float64".to_string(), "bool" => "bool".to_string(), "char" => "rune".to_string(), "string" => "string".to_string(), "()" => "struct{}".to_string(), _ => n.clone() },
            Type::Generic { name, args } => { let a: Vec<String> = args.iter().map(|t| self.type_str(t)).collect(); format!("{}[{}]", name, a.join(", ")) }
            Type::Slice(inner) | Type::Array { inner, .. } => format!("[]{}", self.type_str(inner)),
            _ => "interface{}".to_string(),
        }
    }

    fn gen_expr_to_string(&mut self, expr: &Expr) -> String { let s = self.output.len(); self.gen_expr(expr); let r = self.output[s..].to_string(); self.output.truncate(s); r }
}

fn to_pascal(s: &str) -> String { s.split('_').map(|w| { let mut c = w.chars(); match c.next() { None => String::new(), Some(f) => f.to_uppercase().collect::<String>() + c.as_str() } }).collect() }

impl CodeGenerator for GoCodeGen {
    fn generate(&mut self, program: &Program) -> String { self.generate_go(program) }
    fn target_name(&self) -> &str { "go" }
    fn file_extension(&self) -> &str { ".go" }
}
