use crate::ast::*;
use crate::backend::CodeGenerator;
use std::fmt::Write;

/// Java code generator — transpiles Ruva AST to Java source code.
///
/// Java is a natural fit for Ruva since Ruva's class/OOP syntax mirrors Java closely.
pub struct JavaCodeGen {
    output: String,
    indent: usize,
}

impl JavaCodeGen {
    pub fn new() -> Self {
        Self { output: String::with_capacity(4096), indent: 0 }
    }

    fn write_indent(&mut self) {
        for _ in 0..self.indent { self.output.push_str("    "); }
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        writeln!(self.output, "{}", s).unwrap();
    }

    fn write(&mut self, s: &str) { self.output.push_str(s); }

    pub fn generate_java(&mut self, program: &Program) -> String {
        self.writeln("// Generated by the Ruva transpiler (Java backend) — do not edit");
        self.writeln("");
        for item in &program.items { self.gen_item(item); }
        std::mem::take(&mut self.output)
    }

    fn gen_item(&mut self, item: &Item) {
        match item {
            Item::Function(f) => self.gen_function(f),
            Item::Struct(s) => self.gen_struct(s),
            Item::Class(c) => self.gen_class(c),
            Item::Enum(e) => self.gen_enum(e),
            Item::Impl(imp) => self.gen_impl(imp),
            Item::Trait(t) => self.gen_trait(t),
            Item::TypeAlias(ta) => self.gen_type_alias(ta),
            Item::Import(imp) => self.gen_import(imp),
            Item::Module(m) => self.gen_module(m),
            _ => self.writeln("// Unsupported item"),
        }
    }

    fn gen_function(&mut self, f: &FunctionDef) {
        let vis = if f.is_pub { "public " } else { "" };
        let static_kw = if !f.is_pub { "private " } else { "" };
        let ret = match &f.return_type {
            Some(ty) => format!(" {}", self.type_str(ty)),
            None => " void".to_string(),
        };
        let params: Vec<String> = f.params.iter().map(|p| {
            if let Type::SelfType = &p.ty { "this".to_string() }
            else { format!("{} {}", self.type_str(&p.ty), p.name) }
        }).collect();
        self.writeln(&format!("{}{}static {}({}){} {{", vis, static_kw, f.name, params.join(", "), ret));
        self.indent += 1;
        self.gen_block(&f.body);
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn gen_struct(&mut self, s: &StructDef) {
        let pub_kw = if s.is_pub { "public " } else { "" };
        let field_strs: Vec<String> = s.fields.iter().map(|f| {
            let ty = self.type_str(&f.ty);
            format!("{} {}", ty, f.name)
        }).collect();
        self.writeln(&format!("{}record {}({}) {{", pub_kw, s.name, field_strs.join(", ")));
        self.writeln("}");
        self.writeln("");
    }

    fn gen_enum(&mut self, e: &EnumDef) {
        self.writeln(&format!("public enum {} {{", e.name));
        self.indent += 1;
        for (i, v) in e.variants.iter().enumerate() {
            let comma = if i < e.variants.len() - 1 { "," } else { ";" };
            if v.fields.is_empty() {
                self.writeln(&format!("{}{}", v.name, comma));
            } else {
                let tys: Vec<String> = v.fields.iter().map(|t| self.type_str(t)).collect();
                self.writeln(&format!("{}({}){}", v.name, tys.join(", "), comma));
            }
        }
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn gen_class(&mut self, c: &ClassDef) {
        let pub_kw = if c.is_pub { "public " } else { "" };
        self.writeln(&format!("{}class {} {{", pub_kw, c.name));
        self.indent += 1;
        for f in &c.fields {
            let pub_kw = if f.is_pub { "public " } else { "private " };
            let ty_str = self.type_str(&f.ty);
            self.writeln(&format!("{}{} {};", pub_kw, ty_str, f.name));
        }
        if !c.fields.is_empty() {
            self.writeln("");
        }
        for m in &c.methods { self.gen_function(m); }
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn gen_impl(&mut self, imp: &ImplBlock) {
        let ty = self.type_str(&imp.self_type);
        let iface = imp.trait_name.as_ref().map(|t| format!(" implements {}", self.type_str(t))).unwrap_or_default();
        self.writeln(&format!("// impl {}{}", ty, iface));
        for m in &imp.methods { self.gen_function(m); }
    }

    fn gen_trait(&mut self, t: &TraitDef) {
        self.writeln(&format!("public interface {} {{", t.name));
        self.indent += 1;
        for m in &t.methods {
            let ret = match &m.return_type { Some(ty) => format!(" {}", self.type_str(ty)), None => " void".to_string() };
            let params: Vec<String> = m.params.iter().map(|p| format!("{} {}", self.type_str(&p.ty), p.name)).collect();
            self.writeln(&format!("{}({}){};", m.name, params.join(", "), ret));
        }
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn gen_type_alias(&mut self, ta: &TypeAliasDef) {
        let ty = self.type_str(&ta.ty); self.writeln(&format!("// type {} = {}", ta.name, ty));
    }

    fn gen_import(&mut self, imp: &ImportDef) {
        self.writeln(&format!("import {};", imp.path.replace("::", ".")));
    }

    fn gen_module(&mut self, m: &ModDef) {
        self.writeln(&format!("// module {}", m.name));
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts { self.gen_stmt(stmt); }
        if let Some(ref expr) = block.expr { self.write_indent(); self.gen_expr(expr); self.output.push('\n'); }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, ty, is_mut: _, value } => {
                let ty_str = ty.as_ref().map(|t| format!(" {} ", self.type_str(t))).unwrap_or_default();
                let pat = self.pattern_str(pattern);
                self.write_indent();
                write!(self.output, "var {}{} = ", ty_str, pat).unwrap();
                self.gen_expr(value);
                self.output.push_str(";\n");
            }
            Stmt::Expr(expr) => { self.write_indent(); self.gen_expr(expr); self.output.push_str(";\n"); }
            Stmt::Return(expr) => {
                self.write_indent();
                if let Some(e) = expr { write!(self.output, "return ").unwrap(); self.gen_expr(e); self.output.push_str(";\n"); }
                else { self.output.push_str("return;\n"); }
            }
            Stmt::If { condition, then_body, else_body } => {
                self.write("if ("); self.gen_expr(condition); self.output.push_str(") ");
                self.gen_block_java(then_body);
                if let Some(ek) = else_body {
                    match ek {
                        ElseKind::If(c, b) => { self.write(" else if ("); self.gen_expr(c); self.output.push(' '); self.gen_block_java(b); }
                        ElseKind::Else(b) => { self.write(" else "); self.gen_block_java(b); }
                    }
                }
            }
            Stmt::For { pattern, iterable, body } => {
                let pat = self.pattern_str(pattern);
                self.write_indent(); write!(self.output, "for (var {} : ", pat).unwrap(); self.gen_expr(iterable);
                self.output.push_str(") ");
                self.gen_block_java(body);
            }
            Stmt::While { condition, body } => {
                self.write_indent(); self.output.push_str("while ("); self.gen_expr(condition);
                self.output.push_str(") "); self.gen_block_java(body);
            }
            Stmt::Loop(body) => {
                self.write_indent(); self.output.push_str("while (true) "); self.gen_block_java(body);
            }
            Stmt::Break(_) => { self.writeln("break;"); }
            Stmt::Continue => { self.writeln("continue;"); }
            Stmt::Match { expr, arms } => {
                self.write_indent(); self.output.push_str("switch "); self.gen_expr(expr); self.output.push_str(" {\n");
                self.indent += 1;
                for arm in arms {
                    self.write_indent(); self.output.push_str("case "); let pat_s = self.pattern_str(&arm.pattern); self.gen_expr(&Expr::Ident(pat_s));
                    self.output.push_str(" -> "); self.gen_expr(&arm.body); self.output.push_str(";\n");
                }
                self.indent -= 1; self.writeln("}");
            }
            Stmt::TryCatch { try_body, catch_param, catch_body } => {
                self.writeln("try {"); self.indent += 1; self.gen_block(try_body); self.indent -= 1;
                self.write_indent(); self.writeln(&format!("}} catch (Exception {}) {{", catch_param));
                self.indent += 1; self.gen_block(catch_body); self.indent -= 1; self.writeln("}");
            }
            Stmt::Block(b) => self.gen_block(b),
            Stmt::WhileLet { pattern, value, body } => {
                self.gen_stmt(&Stmt::While { condition: value.clone(), body: body.clone() });
            }
            Stmt::Unsafe(b) => self.gen_block(b),
        }
    }

    fn gen_block_java(&mut self, block: &Block) {
        self.output.push_str("{\n"); self.indent += 1; self.gen_block(block); self.indent -= 1; self.writeln("}");
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n) => write!(self.output, "{}L", n).unwrap(),
            Expr::Float(f) => { let s = format!("{}", f); if !s.contains('.') { write!(self.output, "{}.0", s).unwrap(); } else { write!(self.output, "{}", s).unwrap(); } }
            Expr::Str(s) => write!(self.output, "\"{}\"", s).unwrap(),
            Expr::Char(c) => write!(self.output, "'{}'", c).unwrap(),
            Expr::Bool(b) => { if *b { self.output.push_str("true"); } else { self.output.push_str("false"); } }
            Expr::Null => self.output.push_str("null"),
            Expr::Self_ => self.output.push_str("this"),
            Expr::Ident(n) => self.output.push_str(n),
            Expr::Path(p) => { self.output.push_str(&p.join(".")); }
            Expr::Binary { op, left, right } => { self.output.push('('); self.gen_expr(left); write!(self.output, " {} ", op).unwrap(); self.gen_expr(right); self.output.push(')'); }
            Expr::Unary { op, expr } => { match op { UnaryOp::Neg => self.output.push('-'), UnaryOp::Not => self.output.push_str("!"), _ => {} }; self.gen_expr(expr); }
            Expr::Assign { target, value } => { self.gen_expr(target); self.output.push_str(" = "); self.gen_expr(value); }
            Expr::Call { function, args } => { self.gen_expr(function); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::MethodCall { object, method, args } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(method); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
            Expr::Field { object, field } => { self.gen_expr(object); self.output.push('.'); self.output.push_str(field); }
            Expr::Index { object, index } => { self.gen_expr(object); self.output.push('['); self.gen_expr(index); self.output.push(']'); }
            Expr::Array(elems) => { self.output.push_str("new Object[]{"); for (i, e) in elems.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(e); } self.output.push('}'); }
            Expr::Macro { name, args } => {
                match name.as_str() {
                    "println" => { self.output.push_str("System.out.println("); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                    "print" => { self.output.push_str("System.out.print("); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                    _ => { self.output.push_str(name); self.output.push('('); for (i, a) in args.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.gen_expr(a); } self.output.push(')'); }
                }
            }
            Expr::FString(parts) => {
                self.output.push('"');
                for part in parts { match part { FStringPart::Text(t) => self.output.push_str(t), FStringPart::Expr(e) => { self.output.push_str("\"); System.out.print("); self.gen_expr(e); self.output.push_str("); System.out.print(\""); } } }
                self.output.push('"');
            }
            Expr::Closure { params, body, .. } => {
                self.output.push_str("new Object() { Object f(");
                for (i, p) in params.iter().enumerate() { if i > 0 { self.output.push_str(", "); } self.output.push_str(&p.name); }
                self.output.push_str(") { return "); self.gen_expr(body); self.output.push_str("; } }");
            }
            _ => self.output.push_str("null"),
        }
    }

    fn pattern_str(&mut self, pat: &Pattern) -> String {
        match pat {
            Pattern::Wildcard => "_".to_string(),
            Pattern::Ident(n) => n.clone(),
            Pattern::Literal(e) => self.gen_expr_to_string(e),
            _ => "_".to_string(),
        }
    }

    fn type_str(&mut self, ty: &Type) -> String {
        match ty {
            Type::Name(n) => match n.as_str() {
                "i8" | "i16" | "i32" => "int".to_string(),
                "i64" | "i128" | "isize" => "long".to_string(),
                "u8" | "u16" | "u32" => "int".to_string(),
                "u64" | "u128" | "usize" => "long".to_string(),
                "f32" => "float".to_string(),
                "f64" => "double".to_string(),
                "bool" => "boolean".to_string(),
                "char" => "char".to_string(),
                "string" => "String".to_string(),
                "()" => "void".to_string(),
                _ => n.clone(),
            },
            Type::Generic { name, args } => {
                let a: Vec<String> = args.iter().map(|t| self.type_str(t)).collect();
                format!("{}<{}>", name, a.join(", "))
            }
            Type::Slice(inner) | Type::Array { inner, .. } => format!("List<{}>", self.type_str(inner)),
            Type::Tuple(types) => {
                let t: Vec<String> = types.iter().map(|t| self.type_str(t)).collect();
                format!("Tuple{}", t.join(""))
            }
            _ => "Object".to_string(),
        }
    }

    fn gen_expr_to_string(&mut self, expr: &Expr) -> String {
        let saved = self.output.len(); self.gen_expr(expr);
        let r = self.output[saved..].to_string(); self.output.truncate(saved); r
    }
}

impl CodeGenerator for JavaCodeGen {
    fn generate(&mut self, program: &Program) -> String { self.generate_java(program) }
    fn target_name(&self) -> &str { "java" }
    fn file_extension(&self) -> &str { ".java" }
}
